scale/docs/interface/rest/job_type.rst, scale/docs/interface/rest/port.rst, scale/job/serializers.py, scale/job/test/test_views.py, scale/job/test/utils.py, scale/port/serializers.py, scale/port/test/test_views.py
=> Add max_scheduled to job type views and documentation.

scale/source/models.py, scale/source/test/test_models.py, scale/storage/migrations/0002_workspace_is_move_enabled.py, scale/storage/models.py
Pull request to merge issue #47
=> Allow workspaces to deny file moves

scale-ui/app/test/scripts/backendStubs.js, scale-ui/gulpfile.js, scale-ui/package.json
PR to support random generation of job load for static UI build
=> Static ui updates

scale-ui/app/modules/nodes/models/Node.js
=> Node page doesn't display name properly when only IP Address is available

scale/metrics/migrations/0005_auto_20160415_1636.py, scale/metrics/models.py, scale/metrics/registry.py, scale/metrics/test/test_models.py
Added 3 new columns for job type metrics:
- error_system_count
- error_data_count
- error_algorithm_count
This issue will require a standard DB migration.
Closes #167
=> Issue 167 Job type error metrics

scale/docs/interface/rest/index.rst
=> Issue 154 - Document REST API versioning

scale/docs/rest/product.rst, scale/product/models.py, scale/product/serializers.py, scale/product/test/test_views.py, scale/product/test/utils.py, scale/product/urls.py, scale/product/views.py, scale/source/models.py, scale/source/test/test_views.py, scale/source/urls.py, scale/source/views.py
- Added a new endpoint /products/X/, where X can be either a model id or a file name.
- Response includes the product model details and lists of its associated sources, ancestor products, and descendant products.
Closes #207
=> Issue 207 - Product File Detail API

scale/storage/brokers/exceptions.py, scale/storage/configuration/exceptions.py, scale/storage/configuration/workspace_configuration.py, scale/storage/models.py, scale/storage/test/configuration/test_workspace_configuration.py, scale/storage/test/test_models.py
- Added a configuration JSON schema for workspaces.
- Added a create method to the manager.
=> Issue 222 - Workspace Configuration Validation

scale-ui/app/modules/jobs/partials/jobDetailTemplate.html, scale-ui/app/styles/base.less, scale-ui/app/test/data/job-details/jobDetails1.json, scale-ui/app/test/data/job-details/jobDetails2.json
The first two entries in the jobs grid are failed jobs. The first has a long error message and the second has a short one.
=> Issue #187: Re-position Error Description on Job Detail Page

scale/docs/architecture/workspaces.rst
Updated link for Netshare Docker plugin in docs
=> Issue 264 - Updated link for Netshare Docker plugin in docs

scale/scheduler/test/test_scheduler.py
Fix for the scheduler unit tests
=> Fixed scheduler unit tests

scale/docs/rest/ingest.rst, scale/ingest/serializers.py
This issue was requested when the ingest records table was updated in the UI. After reviewing the code more closely, it seems this was actually already implemented. So I just updated the documentation to make it more clear and fixed some warnings.
=> Issue 230 - Updated REST docs for ingest views.

scale/metrics/registry.py, scale/metrics/test/test_views.py
Updated the aggregate plot calculation to use different logic for min, max, and avg.
=> Issue 252 - Fixed a bug with calculating aggregate values across all records.

scale-ui/app/modules/common/factories/gaugeFactory.js, scale-ui/app/modules/overview/controllers/ovController.js, scale-ui/app/modules/overview/partials/ovTemplate.html, scale-ui/app/styles/base.less
I decided to go with a gray status color when the cluster status is unreachable since that conveys that the status is unknown.  Screenshot attached.
=> Issue #232 - Error Color and Text of Master and Scheduler Status on Overview

scale-ui/app/modules/admin/controllers/adminLoginController.js, scale-ui/app/modules/common/factories/gridFactory.js, scale-ui/app/modules/common/services/stateService.js, scale-ui/app/modules/common/services/userService.js, scale-ui/app/modules/jobs/controllers/jobDetailController.js, scale-ui/app/modules/jobs/controllers/jobsController.js, scale-ui/app/modules/recipes/controllers/recipeDetailsController.js, scale-ui/app/modules/recipes/controllers/recipeTypesController.js, scale-ui/app/modules/recipes/directives/recipeGraphViewerDirective.js, scale-ui/app/test/scripts/backendStubs.js
Fixed state management for sorting and filtering the jobs table.  Also updated the way the admin user object is handled, so we may want to double check that all the "admin" features still show/hide properly.
=> Issue #212 - Job Table Sorting Issue

scale-ui/app/modules/common/services/stateService.js, scale-ui/app/modules/feed/controllers/ingestRecordsController.js, scale-ui/app/modules/jobs/controllers/jobsController.js, scale-ui/app/modules/recipes/controllers/recipesController.js, scale-ui/app/test/scripts/backendStubs.js
Updated recipes and ingest records grids to use stateService.  Load and running grids currently do not have any filtering/sorting capabilities so those were left alone for now.
=> Issue #259 - Table State Issue

scale-ui/app/modules/admin/controllers/adminLoginController.js, scale-ui/app/modules/common/services/stateService.js, scale-ui/app/modules/common/services/userService.js, scale-ui/app/modules/jobs/controllers/jobDetailController.js, scale-ui/app/modules/jobs/controllers/jobsController.js, scale-ui/app/modules/recipes/controllers/recipeTypesController.js
Although I saw this happening on site, I was unable to replicate the issue Paul described in #295.  However I made some adjustments to the login/logout process that I think may be affecting the particular build he is working with.
=> Issue #295 - Recipe editor issues

scale-ui/app/modules/jobs/partials/jobDetailTemplate.html
=> Issue #340 - Job Detail File Link Bug

scale-ui/app/modules/metrics/controllers/metricsController.js
=> Issue #341 - Metrics Unit Conversion

scale-ui/app/modules/charts/grid/gridChartController.js, scale-ui/app/modules/overview/controllers/ovController.js, scale-ui/app/modules/workspaces/partials/workspacesTemplate.html, scale-ui/app/test/data/workspaces/workspace1.json, scale-ui/app/test/data/workspaces/workspace2.json, scale-ui/config/scaleConfig.json
corrected workspace broker fields; bugfix for node page height
=> minor updates

scale-ui/app/modules/app.js, scale-ui/app/modules/common/services/stateService.js, scale-ui/app/modules/load/controllers/loadController.js, scale-ui/app/modules/load/controllers/queueRunningController.js, scale-ui/app/modules/navigation/partials/navTemplate.html, scale-ui/config/scaleConfig.json
=> Issue 284 - Update Queued UI Tab

scale-ui/app/modules/jobs/controllers/jobsController.js
=> Issue 329 - Job re-queue hangs

scale/docs/architecture/workspaces.rst, scale/storage/brokers/s3_broker.py, scale/storage/test/brokers/test_s3_broker.py
Changed S3 broker validation to make the credentials attribute optional and updated associated docs and tests.
=> Issue 360 - Update S3 Broker to allow role-based access

scale-ui/app/modules/workspaces/controllers/workspacesController.js, scale-ui/app/modules/workspaces/models/Workspace.js, scale-ui/app/modules/workspaces/partials/workspacesTemplate.html, scale-ui/app/styles/components/masterdetail.less
=> Issue 363 - Unable to save new workspace

scale/mesos_api/tasks.py, scale/mesos_api/utils.py, scale/pip/dev_win.txt, scale/scheduler/management/commands/scale_scheduler.py, scale/scheduler/scale_scheduler.py, scale/scheduler/threads/db_sync.py, scale/scheduler/threads/recon.py, scale/scheduler/threads/schedule.py
=> Revert "Issue 391 - Mesos.interface could not be imported for new development environments"

scale/pip/build_linux.txt, scale/pip/dev_win.txt, scale/pip/prod_linux.txt
Reviewed boto3 1.4 upgrade notes and ran through unit tests to ensure no breaking changes affected Scale.
=> Updated boto3 dependency.

scale-ui/app/modules/common/services/scaleService.js, scale-ui/app/modules/feed/controllers/ingestRecordsController.js, scale-ui/app/modules/feed/directives/fileAncestryTreeDirective.js, scale-ui/app/modules/feed/directives/fileAncestryTreeTemplate.html, scale-ui/app/modules/feed/partials/ingestRecordDetailsTemplate.html, scale-ui/app/styles/components/dagreDefaults.less, scale-ui/app/styles/main.less, scale-ui/app/test/data/sourceDetails.json
Visualization shows ingested source file on left side of graph, jobs that used it as input and outputs produced from those jobs.
=> Issue 380 - added visualization showing products of ingested sources files

scale-ui/app/modules/charts/grid/gridChartController.js, scale-ui/app/modules/charts/grid/gridChartTemplate.html, scale-ui/app/modules/common/services/stateService.js, scale-ui/app/modules/nodes/controllers/nodesController.js, scale-ui/app/modules/nodes/models/Node.js, scale-ui/app/modules/nodes/models/NodeStatus.js, scale-ui/app/modules/nodes/partials/nodesTemplate.html, scale-ui/app/modules/nodes/services/nodeService.js, scale-ui/app/modules/nodes/services/nodeUpdateService.js, scale-ui/app/modules/overview/controllers/ovController.js, scale-ui/app/test/data/nodes.json, scale-ui/app/test/scripts/backendStubs.js, scale/mesos_api/tasks.py, scale/node/views.py
This needs to be tested with the API changes @dfaller made.
=> Issue 410 - Nodes UI

Dockerfile, README.md, dockerfiles/framework/scale/deployElk.py, scale/error/fixtures/basic_errors.json, scale/job/configuration/configuration/job_configuration.py, scale/job/execution/running/job_exe.py, scale/job/management/commands/scale_post_steps.py, scale/job/models.py, scale/job/test/execution/running/test_job_exe.py
This pull request includes all of the fixes/changes we needed to make for the new logging capability.
=> Logging fixes

scale-ui/app/modules/metrics/controllers/metricsController.js, scale-ui/app/modules/metrics/partials/metricsTemplate.html, scale-ui/app/styles/base.less
Closes #433.  This adds a title, including the selected metric, date range, and count (when applicable). Screenshot:
=> Issue 433 - Metrics Totals

scale-ui/app/modules/recipes/partials/recipeGraphViewerTemplate.html
fixed data_types binding on Recipe trigger edit form.
=> Issue #428 - Fix recipe trigger editor

scale-ui/app/modules/common/services/schedulerService.js, scale-ui/app/modules/common/services/statusService.js, scale-ui/app/modules/feed/services/feedService.js, scale-ui/app/modules/jobs/services/jobExecutionService.js, scale-ui/app/modules/jobs/services/jobService.js, scale-ui/app/modules/jobs/services/jobTypeService.js, scale-ui/app/modules/load/services/loadService.js, scale-ui/app/modules/metrics/services/metricsService.js, scale-ui/app/modules/nodes/services/nodeService.js, scale-ui/app/modules/nodes/services/nodeUpdateService.js, scale-ui/app/modules/recipes/services/recipeService.js, scale-ui/app/modules/scaleConfig.js, scale-ui/app/modules/workspaces/services/workspacesService.js, scale-ui/app/test/scripts/backendStubs.js, scale-ui/config/scaleConfig.json
Pull request for Issue #411. Implemented ability to override API prefix config for 1st level REST endpoints. Included sample config in scaleConfig.json that overrides prefix for /ingests/* calls.
=> Issue #411 - UI API prefix version

scale/scheduler/scale_scheduler.py
closes #359 
If there's no exit code on a task finished, set it to 0.
=> Fix missing exit code

scale-ui/app/modules/common/services/stateService.js, scale-ui/app/modules/feed/controllers/ingestRecordsController.js, scale-ui/app/modules/feed/partials/ingestRecordsTemplate.html
Closes #60 
Wired Search box on Data Feed/Ingests to filter Ingest records on file_name
=> Issue #60 - wired up /api/ingests file_name filter to Search box

scale-ui/app/modules/jobs/models/JobDetails.js, scale-ui/app/modules/jobs/partials/jobDetailTemplate.html, scale-ui/app/styles/base.less
Added Duration to Job Details. Added Job Exit Code and a link to Node on the Executions table.
=> Issue #430 - Add fields to Job Details

scale-ui/app/modules/feed/controllers/strikesController.js, scale-ui/app/modules/feed/models/StrikeIngestFile.js, scale-ui/app/modules/feed/partials/strikesTemplate.html, scale-ui/app/modules/feed/services/strikeService.js
=> Issue 460 - Create Strike UI spins endlessly... errors on console

scale-ui/app/modules/common/services/stateService.js
=> Issue 466 - Remove started/ended from Nodes URL

dockerfiles/framework/scale/deployElk.py, scale/job/configuration/configuration/job_configuration.py
Addresses missing functionality from #442
=> #442 - Adding missing post job connection pool retrieval

README.md, dockerfiles/framework/scale/deployElk.py, dockerfiles/logstash-elastic-ha/logstash.conf-template
Addresses #478 needs for handling reconnection to Logstash following restart.
=> #478 Scheduling following Logstash Restart

scale/docs/rest/recipe.rst, scale/recipe/models.py, scale/recipe/test/test_models.py, scale/recipe/test/test_views.py, scale/recipe/views.py
- Added is_superseded check
- Added corresponding model and view unit tests.
=> Issue 481 - Protect against superseding already superseded recipes

scale/storage/media_type.py
- Added missing extension.
- Fixed formatting.
=> Issue 479 - Add .nitf extension to known media types

scale-ui/app/modules/jobs/controllers/jobDetailController.js, scale-ui/app/modules/jobs/controllers/jobsController.js, scale-ui/app/modules/jobs/models/Job.js, scale-ui/app/modules/jobs/models/JobDetails.js, scale-ui/app/modules/jobs/partials/jobDetailTemplate.html, scale-ui/app/test/data/job-details/jobDetails13.json, scale-ui/app/test/data/jobs.json
Updated Job Details UI to show Superseded details. Completes #344
=> Issue #344 - Updated job details to display superseded info

dockerfiles/logstash-elastic-ha/README.md, dockerfiles/logstash-elastic-ha/elastic_watchdog.py, dockerfiles/logstash-elastic-ha/supervisord.conf
- Added passthrough for Logstash args
- Fix for http_address parsing when hostname and ip:port are present
- Created markdown docs for image usage.
=> #498 - Logstash image improvements

dockerfiles/framework/scale/deployElk.py, dockerfiles/logstash-elastic-ha/logstash.conf-template, scale/docs/architecture/index.rst, scale/docs/architecture/logs.rst, scale/job/configuration/configuration/job_configuration.py, scale/job/models.py
Scale has switched to the syslog logging driver over tcp. Also I standardized the fields that Scale stores in ElasticSearch for long-term compatibility and stability.
=> Issue 462 - tcp syslog logging

scale-ui/app/modules/recipes/models/RecipeDetails.js, scale-ui/app/modules/recipes/partials/recipeDetailsTemplate.html, scale-ui/app/modules/recipes/partials/recipeGraphViewerTemplate.html, scale-ui/app/modules/recipes/services/recipeService.js, scale-ui/app/styles/components/aisRecipe.less, scale-ui/app/test/data/recipe-details/recipeDetail4.json, scale-ui/app/test/data/recipe-details/recipeDetail6.json, scale-ui/app/test/data/recipes.json, scale-ui/app/test/scripts/backendStubs.js
=> Issue #345 - Supersedes info on Recipe Details

scale/product/models.py
Improved performance of FileAncestryLinkManager.get_source_ancestors()
=> Issue 44 - Improved performance of FileAncestryLinkManager.get_source_ancestors()

dockerfiles/framework/scale/dcos_cli.py
These are a few fixes for the logstash deploy.
=> Fixes for the logstash deploy

scale/metrics/migrations/0007_auto_20161013_2333.py, scale/metrics/models.py
Changed all the sum/total count fields to BigInt and generated a corresponding migration.
=> Issue 525 - Metric "sum" fields need to be longs

scale/batch/models.py, scale/batch/serializers.py, scale/batch/test/test_views.py, scale/batch/test/utils.py, scale/batch/urls.py, scale/batch/views.py, scale/docs/rest/batch.rst, scale/docs/rest/index.rst, scale/job/configuration/results/results_manifest/results_manifest.py, scale/scale/urls.py
Added batches list view according to original issue.
=> Issue 63 - Get Batches API

scale-ui/app/modules/common/services/stateService.js, scale-ui/app/modules/jobs/controllers/jobDetailController.js, scale-ui/app/modules/jobs/directives/jobExecutionLogDirective.js, scale-ui/app/modules/jobs/directives/jobExecutionLogTemplate.html, scale-ui/app/modules/jobs/services/jobExecutionService.js, scale-ui/app/test/scripts/backendStubs.js
Bugfixes for properly displaying UI logs
=> Ui log fixes

scale/docs/architecture/django/index.rst, scale/docs/rest/job_execution.rst, scale/job/models.py
Added example response to job execution log API
Also fixed bug so that ES does greater than and equal date searches
=> Issue 527 - Added example response to job execution log API

scale-ui/app/modules/jobs/directives/jobExecutionLogDirective.js, scale-ui/app/test/scripts/backendStubs.js
bugfix to prevent combined endpoint from being called without a started param after the log has started tailing; added logic to remove duplicate log entries; bugfix for static log generation
=> ui-more-log-fixes

scale/batch/models.py, scale/batch/serializers.py, scale/batch/test/test_views.py, scale/batch/urls.py, scale/batch/views.py, scale/docs/architecture/jobs/batch_definition.rst, scale/docs/architecture/jobs/index.rst, scale/docs/rest/batch.rst
Added a new endpoint per the original issue along with corresponding docs and tests.
=> Issue 64 - Get Batch Detail API

.dockerignore, Dockerfile, dockerfiles/framework/scale/dcos_cli.py, dockerfiles/framework/scale/entryPoint.sh, scale-ui/travis-build.sh
- Corrected missing prefix in Apache conf causing all UI assets to request unavailable locations
- Fixed DB_PORT not being passed to WebServer based on DB running in cluster
- Added missing labels to webserver container for exposure of UI via /service/ context of DCOS.
=> Issue 507 fixes

dockerfiles/framework/scale/entryPoint.sh
Remove printouts of shell commands to stderr. Removed SCALE_SECRET_KEY echo
=> #446 - Removing shell command echo

dockerfiles/framework/scale/dcos_cli.py, dockerfiles/framework/scale/entryPoint.sh
- Updated DB deploy to fully apply the the framework name.
- Updated Logstash deploy to persist the full hostname to environment for webserver and scheduler use.
=> #545 - Updates to support framework name customizations

scale-ui/app/modules/feed/controllers/strikesController.js, scale-ui/app/modules/feed/models/StrikeIngestFile.js, scale-ui/app/modules/feed/partials/strikesTemplate.html
=> Issue 555 - Bug in Strike UI

scale/batch/configuration/definition/batch_definition.py, scale/batch/models.py, scale/batch/test/test_models.py, scale/docs/architecture/jobs/batch_definition.rst, scale/recipe/migrations/0015_recipefile.py, scale/recipe/migrations/0016_recipefile_data.py, scale/recipe/models.py, scale/recipe/test/test_models.py
- Added a new RecipeFile model that connects recipes to their input files.
- Created a custom migration to back-fill the recipe file models for all existing recipes.
- Updated create recipe call to also create recipe file models for new recipes.
- Updated the batch definition to allow a data type date range.
- Updated batch system to support the new type of query.
=> Issue 580 - Update batches to support data date

scale-ui/app/modules/metrics/controllers/metricsController.js, scale-ui/app/modules/metrics/partials/metricsTemplate.html, scale-ui/app/styles/base.less
=> Issue 563 - Display Total on Metrics Page

dockerfiles/framework/scale/bootstrap.py
When apps existed for logstash or the webserver from a previous deployment, the bootstrap would fail sometimes causing the app to be removed, but not replaced.
This varied in frequency based on the timing of the deployment task launching within Marathon. The solution is to catch the exception returned by Marathon and attempt to retry up to 3 times. This will catch failures for up to 30 seconds before giving up.
=> #594: Corrected deployment issues caused by pre-existing services.

scale/product/models.py
Updated unpublish product query to be more efficient.
=> Issue - 653 - Unpublish product query is inefficient

scale-ui/app/modules/jobs/directives/jobExecutionLogDirective.js
=> Issue 658 - Log poller doesn't stop when log is closed

scale/scheduler/offer/manager.py, scale/scheduler/offer/node.py, scale/scheduler/test/offer/test_manager.py, scale/scheduler/test/offer/test_node.py, scale/scheduler/threads/schedule.py
This is a critical bug fix for the scheduler. A new unit test has been added that tests for the exact bug.
=> Issue 660 - Bug fix for critical scheduler bug

scale/docs/architecture/jobs/job_type_configuration.rst, scale/job/configuration/configuration/job_configuration.py, scale/job/configuration/configuration/job_parameter.py, scale/job/configuration/interface/configuration_interface.py, scale/job/configuration/interface/job_interface_1_0.py, scale/job/configuration/interface/job_type_configuration.py, scale/job/migrations/0022_jobtype_configuration.py, scale/job/models.py, scale/job/test/configuration/configuration/test_job_configuration.py, scale/job/test/configuration/interface/test_configuration_interface.py, scale/job/test/configuration/interface/test_job_interface.py, scale/job/test/utils.py
This allows for default settings of a job_type to be defined.  This branch also includes a couple changes I made to clean up several files.
=> Issue 665 - Default job type settings

scale/job/configuration/interface/job_interface.py, scale/job/management/commands/scale_pre_steps.py, scale/job/test/configuration/interface/test_job_interface.py, scale/job/test/management/commands/test_scale_pre_steps.py
Simplified the required settings check and added a call to populate the command_args in the pre-task.
=> Fixed settings population and required settings check.

scale/job/execution/running/job_exe.py, scale/job/execution/running/tasks/base_task.py, scale/job/execution/running/tasks/cleanup_task.py, scale/job/execution/running/tasks/update.py, scale/job/test/execution/running/tasks/test_base_task.py, scale/job/test/utils.py, scale/mesos_api/utils.py, scale/scheduler/scale_scheduler.py
This PR improves the Scale Docker cleanup capability by only deleting the specific containers created by a given job execution.
=> Issue 678 - Scale container cleanup

scale/recipe/models.py, scale/recipe/test/test_models.py
This PR is a bug fix for re-processing where new jobs that should have been marked BLOCKED were not being marked BLOCKED (remained PENDING).
=> Issue 711 - Bug fix for re-processed jobs

scale/job/tasks/health_task.py, scale/product/migrations/0007_fileancestrylink_batch.py, scale/product/migrations/0008_auto_20170221_1413.py, scale/product/models.py, scale/product/test/test_models.py
Added a 'docker ps' check to the node health check task.
Also added some command time out constraints to commands in the node health check task.
=> Issue 723 - docker ps check in health task

Dockerfile, dockerfiles/logstash-elastic-ha/Dockerfile, scale-ui/app/modules/app.js, scale-ui/app/modules/batch/controllers/batchDetailsController.js, scale-ui/app/modules/batch/controllers/batchesController.js, scale-ui/app/modules/batch/models/Batch.js, scale-ui/app/modules/batch/partials/batchDetailsTemplate.html, scale-ui/app/modules/batch/partials/batchesTemplate.html, scale-ui/app/modules/batch/services/batchService.js, scale-ui/app/modules/common/services/stateService.js, scale-ui/app/modules/jobs/controllers/jobsController.js, scale-ui/app/modules/jobs/partials/jobTypesFailureRatesTemplate.html, scale-ui/app/modules/jobs/partials/jobsTemplate.html, scale-ui/app/modules/navigation/partials/navTemplate.html, scale-ui/app/styles/pages/jobTypesErrorRates.less, scale-ui/app/styles/variables/colors.less, scale-ui/app/test/data/batch/batches.json, scale-ui/app/test/scripts/backendStubs.js, scale-ui/config/scaleConfig.json, scale/scale/__init__.py, scale/scale/__init__.py.template
Closes #739.  Includes the ability to sort/filter batches, create a batch, and view batch details.  Screenshots below.
=> Issue 739 - Batches UI

scale-ui/app/modules/feed/partials/ingestRecordDetailsTemplate.html
=> Issue 730 - Workspace URL is incorrect when access from ingest records

scale-ui/app/modules/header/headerDirective.js, scale-ui/app/modules/header/headerTemplate.html, scale-ui/app/styles/base.less
=> Issue 746 - Enable subnav while loading

scale/scheduler/cleanup/node.py
=> Issue 748 - Bug fix

scale/scheduler/cleanup/node.py, scale/scheduler/node/conditions.py, scale/scheduler/node/node_class.py, scale/scheduler/test/node/test_node_class.py
This PR fixs a bug where a logstash or low disk space health check failure will cause a node to stay in DEGRADED state indefinitely.
This PR contains a larger general refactor of node errors/warnings (now called conditions) since the bug fix was already part of a refactor that had been started in another branch.
=> Issue 749 - DEGRADED node bug fix

scale-ui/app/modules/feed/directives/fileAncestryTreeDirective.js, scale-ui/app/modules/feed/partials/ingestRecordDetailsTemplate.html, scale-ui/app/styles/components/fileAncestryTree.less, scale-ui/app/styles/main.less
Resolves #763 
Added a border around the tree to delineate the container that pans/zooms.
=> Issue 763 - Enable pan/zoom for file ancestry tree on ingest details view

dockerfiles/framework/scale/bootstrap.py
CORS headers to support remote development of UI against cluster hosted APIs.
=> #781: Added CORS headers

scale/job/models.py
Adding missing mount for Scan system job.
=> #779: Fix to mount workspace to Scan job

scale/queue/models.py, scale/queue/test/test_models.py, scale/queue/test/utils.py, scale/scheduler/migrations/0005_scheduler_queue_mode.py, scale/scheduler/models.py, scale/scheduler/sync/scheduler_manager.py, scale/scheduler/threads/schedule.py
This PR adds a new scheduler field that switches the queue ordering mode between FIFO and LIFO.
=> Issue 794 - Add FIFO/LIFO mode switch to scheduler

scale/ingest/test/test_views.py, scale/ingest/test/utils.py, scale/metrics/models.py, scale/metrics/test/test_models.py
Patched metrics to work with null Strike ingests. Unit tests added to validate.
=> #793: Daily Metrics fix for null Strike relationship.

scale/docs/cli/overview.rst, scale/docs/rest/index.rst, scale/docs/rest/ingest.rst, scale/docs/rest/source_file.rst, scale/ingest/models.py, scale/ingest/serializers.py, scale/scale/settings.py, scale/source/models.py, scale/source/serializers.py, scale/source/serializers_extra.py, scale/source/test/test_models.py, scale/source/test/test_views.py, scale/source/urls.py, scale/source/views.py
This PR:
1. Creates a new v5 version of the source file detail API to be faster by stripping out ingests and products
2. Creates a new API for returning ingests related to a source file
3. Reworks the fields returned for ingest and ingest detail APIs
=> Issue 797 - v5 Source File Details REST API

scale-ui/app/modules/batch/controllers/batchDetailsController.js, scale-ui/app/modules/batch/controllers/batchesController.js, scale-ui/app/modules/batch/partials/batchDetailsTemplate.html, scale-ui/app/modules/batch/partials/batchesTemplate.html, scale-ui/app/styles/base.less, scale-ui/app/styles/main.less, scale-ui/app/styles/pages/batches.less, scale-ui/config/scaleConfig.json
This addresses most of the problems described in #791 (and also closes #769).  There are some items remaining (see issue thread for details), but it would be ideal to get these fixes in for the current sprint.
=> Issue 791 - Batch UI Issues

dockerfiles/vault-dcos/Dockerfile
Updated the dockerfile for vault-dcos to change permissions on the shell script.
=> #804: vault-dcos deploy errors

.gitignore, .travis.yml, scale/.gitignore, travis-build.sh
Results can be seen here: https://codecov.io/gh/ngageoint/scale
=> Added code coverage calculation

scale-ui/app/modules/batch/controllers/batchesController.js, scale-ui/app/modules/feed/controllers/ingestRecordsController.js, scale-ui/app/modules/jobs/controllers/jobsController.js, scale-ui/app/modules/nodes/controllers/nodesController.js, scale-ui/app/modules/recipes/controllers/recipesController.js, scale-ui/app/test/scripts/backendStubs.js
Fixes #808.  Also fixes a bug where multiple pollers would be running after filtering or sorting grid results.  There's really no screenshot that is applicable to this PR.
=> Issue 808 - UI Grid pagination

scale-ui/app/modules/jobs/models/JobTypeDetails.js, scale-ui/app/modules/jobs/partials/jobTypesTemplate.html, scale-ui/app/styles/components/masterdetail.less, scale-ui/app/test/data/job-details/jobDetails1.json, scale-ui/app/test/data/job-details/jobDetails10.json, scale-ui/app/test/data/job-details/jobDetails11.json, scale-ui/app/test/data/job-details/jobDetails12.json, scale-ui/app/test/data/job-details/jobDetails13.json, scale-ui/app/test/data/job-details/jobDetails2.json, scale-ui/app/test/data/job-details/jobDetails3.json, scale-ui/app/test/data/job-details/jobDetails4.json, scale-ui/app/test/data/job-details/jobDetails5.json, scale-ui/app/test/data/job-details/jobDetails6.json, scale-ui/app/test/data/job-details/jobDetails7.json, scale-ui/app/test/data/job-details/jobDetails8.json, scale-ui/app/test/data/job-details/jobDetails9.json, scale-ui/app/test/data/job-types/jobType1.json, scale-ui/app/test/data/job-types/jobType10.json, scale-ui/app/test/data/job-types/jobType11.json, scale-ui/app/test/data/job-types/jobType12.json, scale-ui/app/test/data/job-types/jobType2.json, scale-ui/app/test/data/job-types/jobType3.json, scale-ui/app/test/data/job-types/jobType4.json, scale-ui/app/test/data/job-types/jobType5.json, scale-ui/app/test/data/job-types/jobType6.json, scale-ui/app/test/data/job-types/jobType7.json, scale-ui/app/test/data/job-types/jobType8.json, scale-ui/app/test/data/job-types/jobType9.json
Resolves #783.  I also removed the fixed height of the details portion of the page.  It isn't really necessary and produced an ugly double-scrollbar due to the height of the side navigation.
=> Issue 783 - Add shared memory field to job detail page

scale-ui/app/modules/batch/controllers/batchDetailsController.js, scale-ui/app/modules/batch/controllers/batchesController.js, scale-ui/app/modules/batch/partials/batchDetailsTemplate.html, scale-ui/app/modules/batch/partials/batchesTemplate.html, scale-ui/config/scaleConfig.json
Resolves #818.  Create button used to be in subnav area.  Now it's next to the title, and the subnav has been removed.
=> Issue 818 - Batch UI - move create button

scale/job/execution/tasks/cleanup_task.py
Address #836. Issue identified by @elviento. Thanks!
=> Updated docker volume cleanup to only address scale volumes

scale/queue/models.py, scale/scheduler/threads/schedule.py
Updated the scheduler to only look at the top 500 jobs on the queue.
=> Issue 845 - Queue performance improvement

scale/docs/rest/scan.rst
=> Added recursive flag to REST API docs.

scale/ingest/strike/monitors/s3_monitor.py, scale/ingest/test/strike/monitors/test_s3_monitor.py
=> Relaxed Strike checks on input S3 event notifications.

web-docs/quickstart.html
=> Updated quickstart to clarify workspace usage.

scale-ui/app/modules/charts/donut/donutController.js, scale-ui/app/modules/nodes/controllers/nodesController.js, scale-ui/app/modules/nodes/partials/nodesTemplate.html, scale-ui/app/test/scripts/backendStubs.js
Includes a few bugfixes and adjustments to support #823
=> Additional Node Status updates for Issue 823

scale-ui/app/modules/nodes/controllers/nodeDetailsController.js, scale-ui/app/modules/nodes/partials/nodeDetailsTemplate.html, scale-ui/app/modules/nodes/partials/nodesTemplate.html
=> Issue 867 - Node Detail Page Bug

scale-ui/app/modules/recipes/controllers/recipeDetailsController.js, scale-ui/app/modules/recipes/directives/recipeGraphViewerDirective.js, scale-ui/app/test/data/recipe-details/recipeDetail1.json, scale-ui/app/test/data/recipe-details/recipeDetail2.json, scale-ui/app/test/data/recipe-details/recipeDetail3.json, scale-ui/app/test/data/recipe-details/recipeDetail4.json, scale-ui/app/test/data/recipe-details/recipeDetail5.json, scale-ui/app/test/data/recipe-details/recipeDetail6.json, scale-ui/app/test/data/recipes.json
Closes #655 
Planning to test this against live data before it is merged.
=> Issue 655 - UI recipe detail page bugs

scale-ui/config/scaleConfig.json
Just a small bugfix to get ingest details working again.  Don't delete this branch after this PR is merged.
=> Issue 876 - Source File Data UI

scale/queue/models.py, scale/scheduler/test/scheduling/test_manager.py
=> Issue 883 - Bug fix for job type pausing

scale-ui/app/modules/recipes/controllers/recipeDetailsController.js, scale-ui/app/modules/recipes/models/RecipeTypeDetail.js
Temporary fix for #894. This will at least show recipe details until the control can be modified further to include proper job information.
=> Issue 894 - Recipe detail bug

scale-ui/app/modules/common/services/stateService.js, scale-ui/app/modules/data/controllers/sourceFileDetailsController.js, scale-ui/app/modules/feed/controllers/feedDetailsController.js, scale-ui/app/modules/jobs/controllers/jobTypesFailureRatesController.js, scale-ui/app/modules/navigation/controllers/navController.js, scale-ui/app/modules/nodes/controllers/nodesController.js
=> Issue 889 - Browser back button problems

scale/batch/test/utils.py, scale/docs/rest/job.rst, scale/docs/rest/recipe.rst, scale/job/models.py, scale/job/test/test_views.py, scale/job/views.py, scale/recipe/models.py, scale/recipe/test/test_views.py, scale/recipe/views.py, scale/source/models.py, scale/source/test/test_views.py, scale/source/views.py
* Added batch_id filtering to /jobs/ API 
* Added batch_id filtering to /recipes/ API 
* Updated docs to reflect changes
=> #850 - Allow jobs and recipes to be filter by batch

scale/docs/rest/system.rst, scale/scheduler/manager.py, scale/scheduler/node/node_class.py
Added a scheduler status (Paused/Ready) to the /v5/status/ REST API.
=> Issue 911 - Scheduler Status

Dockerfile
Removed Apache welcome content and default conf.d files to address security scan concerns.
=> Removed Apache web server welcome content.

scale/docs/index.rst
Added about blurb to docs home page
=> Added about section

scale/docs/_static/style.css, scale/docs/_templates/layout.html
Took the CSS provided by @ericsvendsen  and put it on a layout that extends all ReadTheDocs pages.
=> #901 - Fix max width of docs

Dockerfile, dockerfiles/framework/scale/app-templates/db.json, dockerfiles/framework/scale/app-templates/logstash.json, dockerfiles/framework/scale/app-templates/rabbitmq.json, dockerfiles/framework/scale/app-templates/webserver.json, dockerfiles/framework/scale/bootstrap.py, dockerfiles/logstash/Dockerfile, dockerfiles/logstash/README.md, dockerfiles/logstash/elastic_watchdog.py, dockerfiles/logstash/logstash.conf-template, dockerfiles/logstash/supervisord.conf, scale/diagnostic/management/commands/scale_hello.py
Ultimately I am unable to reproduce the stderr/stdout issues outlined in #878. I made some updates to our logstash image and to the Scale Hello job to diagnose.
- Updated Scale Hello to output 2 messages: one on stderr, one on stdout.
- Updated `scale-logstash` image to take LOGSTASH_DEBUG environment variable. When set to `true` this will echo all message payloads received to the console.
- Updated `scale-logstash` image to use Alpine linux. Reduced image size by ~250MB
- Updated bootstrap.py to move all marathon.json templates out of code.
=> #878: Debug additions for logging subsystem.

scale-ui/app/styles/base.less, scale-ui/package.json
Fix long text overflowing on all tables, including ones in modals
=> Fix table overflow issue

scale/product/views.py
Updated to support `v4` call in product API
=> #932 - product API bug fix

scale/ingest/strike/monitors/monitor.py, scale/ingest/test/strike/monitors/test_dir_monitor.py
=> Set ingests to DEFERRED if no rules matched

.travis.yml, Dockerfile, dockerfiles/logstash/Dockerfile, dockerfiles/vault-dcos/Dockerfile, generate-release.sh, travis-build.sh
#957: Enable configuration of base images by setting `--build-arg IMAGE=new-image` on Docker Build.
#957: Enable configuration VAULT_ZIP location with `--build-arg VAULT_ZIP=zip-location` on Docker Build
=> Added ARG for configuration of base image

scale/scheduler/vault/manager.py
The discovered secrets are never being set back to the class. 
🐛 🐞 🐛
=> fixed Scale scheduler secrets cache bug

scale/job/models.py, scale/product/models.py, scale/scheduler/database/updater.py, scale/scheduler/management/commands/scale_db_update.py
1. Updated the JobExecution model to check for strings in the configuration and resources JSON fields. When the column was updated from json to jsonb, it appears some values come back as strings instead of dicts in Django.
2. Updated ProductFileManager.populate_source_ancestors() to be more efficient. Removed the file_type == 'SOURCE' condition from the query and did that filtering ourselves because that filtering in the database causes the query to perform very poorly.
3. Made exception handling more generic in the Scale Database Update task and fixed bug where retrieving stdout and stderr columns caused the Docker container to run out of memory.
=> Issue 968 - Minor bug fixes

scale/recipe/handlers/graph_delta.py, scale/recipe/test/handlers/test_graph_delta.py
Updated recipe handling to detect changed jobs from one recipe definition to another.
=> Issue 656 - Update recipe handling to recognize "changed" jobs

scale/error/models.py, scale/job/execution/manager.py, scale/job/test/execution/test_manager.py, scale/job/test/messages/test_job_exe_end.py, scale/messaging/manager.py
Updated the job execution manager to submit all job_exe_end model creation through the backend messaging system.
=> Issue 974 - Handle all job_exe_end models through messaging

scale-ui/app/modules/jobs/controllers/jobsController.js
=> Issue 978 - Jobs grid "requeue all" button

scale/job/configuration/configurators.py, scale/job/test/configuration/test_configurators.py
Fixed bug where optional input substitutions were not removed
=> Issue 980 - Bug fix for optional input substitutions

.travis.yml, Dockerfile, dockerfiles/logstash/Dockerfile, hooks/build, travis-build.sh
Cleaned up unneeded labels and added hooks for Docker Cloud builds.
=> Docker image cleanup

scale/storage/test/test_views.py
Updated workspace id to get details for.
=> #987 - Modify Workspace tests to avoid random collision

scale/product/models.py
Bug fixes for performance that were exposed by a large number of cross links in the file ancestry link table.
=> Issue 994 - Performance fix for large file ancestries

scale/job/execution/tasks/cleanup_task.py, scale/job/tasks/pull_task.py
=> #951 - Docker pull tasks fail if dangling image cleanup fails

scale/job/configuration/configurators.py, scale/queue/migrations/0015_auto_20170731_1527.py
Quick bug fix for the most recent data migration that rebuilds the queue
=> Issue 1002 - Fixed queue migration bug

scale/error/models.py, scale/job/test/test_views.py
Bug fix for jobs with builtin errors
=> Issue 1052 - Bug fix for jobs using builtin errors

scale/job/messages/job_exe_end.py, scale/job/test/messages/test_job_exe_end.py
Updated job_exe_end message to handle duplicate models.
If approved, please merge and delete branch.
=> Issue 1056 - Update message to handle duplicate models

scale/messaging/manager.py, scale/messaging/test/test_manager.py
Bug fix to handle command messages that throw exceptions
If approved, please go ahead and merge and delete the branch.
=> Issue 1054 - Message handlers don't handle message exceptions

scale/job/models.py, scale/recipe/test/messages/test_update_recipes.py
Fixed critical bug in recipe update message when job input was passed to child jobs
=> Issue 1079 - Critical bug in recipe update message

scale-ui/app/modules/data/controllers/sourceFilesController.js, scale-ui/app/modules/data/partials/sourceFilesTemplate.html
=> Issue 1076 - Add option to disable date filter on Source Files

scale-ui/app/modules/common/services/stateService.js, scale-ui/app/modules/data/controllers/sourceFileDetailsController.js, scale-ui/app/modules/feed/controllers/ingestRecordsController.js, scale-ui/app/modules/jobs/controllers/jobsController.js
=> Issue 1075 - Remove date filter from data detail

scale-ui/app/modules/jobs/models/JobDetails.js
=> Issue 1108 - Unable to view failed job details

scale-ui/app/modules/jobs/models/JobDetails.js
=> Issue 1108 - Unable to view failed job details pt 2

scale/docs/rest/job.rst, scale/docs/rest/queue.rst, scale/job/models.py, scale/job/test/test_models.py, scale/job/test/test_views.py, scale/job/test/utils.py, scale/job/urls.py, scale/job/views.py, scale/queue/apps.py, scale/queue/messages/queued_jobs.py, scale/queue/messages/requeue_jobs.py, scale/queue/messages/requeue_jobs_bulk.py, scale/queue/models.py, scale/queue/test/messages/test_requeue_jobs.py, scale/queue/test/messages/test_requeue_jobs_bulk.py, scale/queue/test/test_views.py, scale/queue/urls.py, scale/queue/views.py, scale/source/models.py
I created two new messages to handle re-queuing jobs and created a new re-queue jobs API (in the jobs app) that sends a message to perform the re-queue and quickly responds. I deprecated the old re-queue jobs API (in the queue app).
=> Issue 183 - Refactor Job Requeue

scale/job/views.py
Bug fix for new requeue jobs message
=> Bug fix for new requeue jobs message

scale/scheduler/database/updater.py, scale/scheduler/test/database/test_updater.py
Bug fix for updating old batches with recipe_type_rev_id
=> Bug fix for Issue 670

scale-ui/app/modules/common/services/stateService.js, scale-ui/app/modules/jobs/controllers/jobsController.js, scale-ui/app/modules/jobs/partials/jobsTemplate.html
Added `include_superseded` toggle switch to jobs table for #1100
=> Issue 1100 - Toggle superseded jobs

scale/pip/production.txt, scale/pip/requirements.txt
=> Issue 1184 - Update python dependencies to remove security vulnerabilities

scale/docs/rest/index.rst, scale/docs/rest/v6/metrics.rst, scale/docs/rest/v6/metrics.yml, scale/metrics/test/test_views.py, scale/metrics/views.py
=> 1135 v6 metrics rest

scale/docs/rest/port.rst, scale/port/test/test_views.py, scale/port/views.py
Limiting Import/Export to v5 of REST API
=> 1137 Deprecating Import/Export REST API

scale/docs/rest/index.rst, scale/docs/rest/v6/node.rst, scale/docs/rest/v6/node.yml, scale/node/models.py, scale/node/test/test_views.py, scale/node/views.py
=> 1136 v6 node rest api changes

scale/docs/rest/index.rst, scale/docs/rest/v6/ingest.rst, scale/docs/rest/v6/ingest.yml, scale/ingest/test/test_views.py, scale/ingest/views.py
Lots of stuff to review here, but on the bright side, scan/scale/workspace/source file/etc openapi reviews should be much easier to review as they're mostly done here.
=> v6 Ingest rest api

README.md
Recreated bower_components.tar.gz to fix #1200
=> Issue 1200 - update bower_components.tar.gz

scale-ui/config/scaleConfig.json
=> Issue 1215 - Update scheduler API prefix

dockerfiles/examples/test-seed/seed.manifest.json, scale/job/seed/manifest.py, scale/job/seed/schema/seed.manifest.schema.json, scale/job/seed/schema/seed.metadata.schema.json, scale/job/test/test_models.py, scale/job/test/utils.py
=> Seed 1.0.0 error name field addition

scale/error/models.py, scale/error/test/test_models.py
=> Issue 1236 - Fix error caching bug

scale/job/models.py, scale/job/test/utils.py, scale/queue/test/test_models.py
Fixed bug with triggering/queuing Seed jobs
=> Issue 1238 - Fix bug with triggering Seed jobs

scale/job/management/commands/scale_pre_steps.py, scale/job/models.py, scale/job/test/management/commands/test_scale_pre_steps.py
Fixed a bug in Seed job pre-task if it is presented with a legacy job data class.
Also fixed an additional bug that I noticed. 
This has already been tested in the dev environment.
=> Issue 1240 - Fix bug in Seed job pre-task

scale/job/data/job_data.py, scale/job/models.py
Fixed two bugs with the v5 job details API when viewing Seed jobs.
=> Issue 1242 - Fix v5 job details bugs

scale/job/models.py, scale/job/seed/results/job_results.py, scale/queue/test/test_models.py
Fixed bug passing Seed job results to legacy job results
=> Issue 1245 - Fixed bug passing Seed job results to legacy job results

scale/util/command.py, scale/util/test/test_command.py
Fixed bug with command expansion for optional arguments
=> Issue 1248 - Fixed bug with command expansion for optional arguments

scale/job/execution/configuration/configurators.py, scale/util/command.py, scale/util/test/test_command.py
Fixed bug where the job output directory was removed without being set
=> Issue 1252 - Fixed bug with removing job output directory

scale/queue/messages/requeue_jobs_bulk.py, scale/queue/test/messages/test_requeue_jobs_bulk.py
Fixed requeue_jobs_bulk message to handle uncanceling jobs.
If approved, please go ahead and merge and delete branch.
=> Issue 1254 - Fixed requeue_jobs_bulk message to handle uncanceling jobs

scale/job/seed/schema/seed.manifest.schema.json
=> Seed 1.0.0 schema

scale-ui/app/modules/overview/controllers/ovController.js, scale-ui/app/modules/overview/partials/ovTemplate.html
=> Issue 1278 - Remove resource scaling

scale/batch/serializers.py, scale/docs/rest/index.rst, scale/docs/rest/v6/job.rst, scale/docs/rest/v6/job.yml, scale/docs/rest/v6/job_type.yml, scale/ingest/serializers.py, scale/job/job_type_serializers.py, scale/job/models.py, scale/job/serializers.py, scale/job/test/test_views.py, scale/job/views.py, scale/metrics/serializers.py, scale/product/serializers.py, scale/queue/serializers.py, scale/queue/views.py, scale/recipe/serializers.py, scale/recipe/test/test_views.py, scale/recipe/views.py, scale/source/models.py, scale/storage/serializers.py, scale/trigger/serializers.py
Updating v6 jobs list api.
Made some updates for job details serializer
Reorganized job type serializers into their own file to fix circular imports.
Added v6 recipe tests due to job serializer changes
=> 1113 v6 jobs list

scale/job/models.py, scale/job/test/test_views.py, scale/job/views.py
Fix for the bug Emily found yesterday.
=> Fixing bug and adding test case for it

scale/job/models.py, scale/job/test/test_views.py
=> 1290 maintainer url

scale-ui/app/modules/jobs/controllers/jobsController.js
=> Issue 1300 - Query by id when filtering jobs table by job type name and version

.gitignore, scale/job/views.py, scale/storage/fixtures/delete_files_job_type.json, scale/storage/management/commands/scale_delete_files.py, scale/storage/messages/delete_files.py, scale/storage/test/fixtures/test_delete_files_job_type.py, scale/storage/test/management/commands/test_scale_delete_files.py, scale/storage/test/messages/test_delete_files.py
- 👕 pylint pep8 fixes on `scale/job/views.py`
- Updated fixture to be seed compliant
- Refactored delete_files to accept JSON via environment variables
- Updated tests + added fixture test for validating the Seed 🌱  manifest
=> #1308 - Seedify delete_files SYSTEM job

scale-ui/app/modules/feed/controllers/ingestRecordDetailsController.js, scale-ui/app/modules/feed/models/Ingest.js, scale-ui/app/styles/components/fileAncestryTree.less
Fixes #1326
The UI now retrieves the ingest details using the ingest ID, and then gets the source details using the source_file ID.
=> Issue 1326 - Ingest detail

.gitignore, scale/job/apps.py, scale/job/execution/configuration/configurators.py, scale/job/messages/purge_jobs.py, scale/job/messages/running_jobs.py, scale/job/messages/spawn_delete_files_job.py, scale/job/seed/manifest.py, scale/job/test/messages/test_spawn_delete_files_job.py, scale/storage/fixtures/delete_files_job_type.json, scale/storage/management/commands/scale_delete_files.py, scale/storage/messages/delete_files.py
- Added JobTypeRev fixture for `scale-delete-files`
- Added command message `spawn-delete-files-job` for creating and queuing a system job that will delete files in workspaces
I will update the wiki after approval but before merge.
=> #1209 - Delete job files message

scale-ui/app/modules/common/services/stateService.js
=> Issue 1327 - Change all grid intervals to 24 hours

scale/scheduler/node/node_class.py, scale/scheduler/test/node/test_manager.py
Expanded node reset to include resetting all of the node's state.
=> Issue 1347 - Expanded node reset

scale/job/job_type_serializers.py, scale/job/models.py, scale/job/serializers.py, scale/job/test/test_models.py, scale/job/test/test_views.py, scale/job/views.py, scale/recipe/serializers.py, scale/recipe/test/test_views.py, scale/recipe/views.py
- Added `is_seed_job_type` function to `JobType` that will return a bool stating if the job_type is seed compliant. 
- Added convert logic to `JobTypeManager` that allows a Seed interface to be returned on `v5` API requests. 
- Added `is_seed_job_type` check and convert logic to `v5` `recipe-type` details API call.
- Added `is_seed_job_type` check and convert logic to `v5` `job-type` details API call.
❤️ Made some PEP8 fixes ✨
=> #1350 - Fix job/recipe editors

scale/product/models.py, scale/product/test/test_models.py
Leaving the environment variable changes for another PR when we change all of the post task stuff.
=> Setting source metadata on product upload

scale/job/models.py, scale/job/test/test_views.py, scale/job/test/utils.py, scale/job/views.py
=> 1334 block v5 edit

scale/README.md, scale/environment/cloud-init.sh
#1343: Resolved issues when using Cloud9 on Amazon Linux. Removed mentions to pre-AWS Cloud9 and CloudAnywhere as those services are now defunct.
=> #1343 - Cloud init fix

scale/README.md, scale/environment/legacy-cloud-init.sh
Adding back script for pre-AWS Cloud9
=> Added script for legacy cloud9

scale/job/test/messages/test_create_jobs.py, scale/recipe/apps.py, scale/recipe/messages/create_conditions.py, scale/recipe/models.py, scale/recipe/test/messages/test_create_conditions.py
Added a new message to create recipe condition models.
=> Issue 1382 - Message to create recipe conditions

scale/recipe/messages/process_condition.py, scale/recipe/messages/update_recipe.py, scale/recipe/test/messages/test_update_recipe.py
Updated update_recipe message to handle sending messages to create and process recipe conditions
=> Issue 1175 - Handle recipe conditions in update_recipe message

scale/scheduler/node/node_class.py, scale/scheduler/test/node/test_manager.py, scale/scheduler/test/node/test_node_class.py, scale/scheduler/test/scheduling/test_manager.py
Fixing the bug with _last_heath_check set to None
=> Fixing heath check

scale/scheduler/scheduling/manager.py, scale/scheduler/test/scheduling/test_manager.py
Removing the scheduler check/log output
=> #1321 removing incorrect check in scheduler

scale/job/data/job_data.py
Updated `job.data.job_data` `extend_interface_with_inputs_v5()` and `extend_interface_with_inputs()` to reflect the change to the file_value schema in PR #1416 for issue #1409
=> Referencing file_ids properly

scale/job/models.py
=> fixed elasticsearch log spamming

dockerfiles/framework/scale/app-templates/db.json, dockerfiles/framework/scale/bootstrap.py, scale/README.md
Needed support to deploy within a cluster requiring Scale to be contained within a Marathon application group.
=> Adding support for application grouped deployment

scale/docs/rest/v6/job_type.rst, scale/docs/rest/v6/job_type.yml, scale/docs/rest/v6/recipe_type.rst, scale/docs/rest/v6/recipe_type.yml, scale/job/job_type_serializers.py, scale/job/models.py, scale/job/test/test_views.py, scale/job/views.py, scale/recipe/models.py, scale/recipe/test/test_views.py, scale/recipe/views.py
Fixes for issues #1440, #1422 and #1390
EDIT: also #1435
=> 1422 job type versions

scale/docs/rest/system.rst, scale/docs/rest/v6/system.rst, scale/docs/rest/v6/system.yml, scale/scheduler/test/test_views.py, scale/scheduler/threads/scheduler_status.py, scale/scheduler/vault/manager.py, scale/vault/exceptions.py, scale/vault/secrets_handler.py
Adding vault status to status api
=> 1359 secret status

scale/docs/rest/v6/job.rst, scale/docs/rest/v6/job.yml, scale/job/test/test_views.py, scale/job/views.py, scale/util/rest.py, scale/util/test/test_rest.py
Changes for issue #1434 and #1454
=> 1434 requeue job type

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, scale/README.md
None
Moved the 'Definition of Done' statement to the new contributing guide and added a PR template
=> #1446 - Contribution guidelines

scale/data/data/exceptions.py, scale/data/filter/filter.py, scale/data/filter/json/filter_v6.py, scale/data/test/filter/json/test_filter_v6.py, scale/data/test/filter/test_filter.py, scale/docs/rest/v6/data.rst, scale/docs/rest/v6/data.yml, scale/recipe/definition/json/definition_v6.py, scale/recipe/test/definition/test_definition.py, scale/recipe/test/diff/json/test_diff_v6.py, scale/recipe/test/diff/test_diff.py, scale/recipe/test/instance/json/test_recipe_v6.py, scale/recipe/test/instance/test_recipe.py, scale/recipe/test/messages/test_process_condition.py, scale/recipe/test/messages/test_purge_recipe.py, scale/recipe/test/messages/test_update_recipe.py
- data
- recipe
Adding data filter class and json schema
=> #1384 - Implement data filters

scale/data/filter/json/filter_v6.py, scale/docs/rest/v6/recipe_type.rst, scale/docs/rest/v6/recipe_type.yml, scale/recipe/definition/json/definition_v6.py, scale/recipe/definition/node.py, scale/recipe/test/definition/json/test_definition_v6.py, scale/recipe/test/definition/test_definition.py, scale/recipe/test/diff/json/test_diff_v6.py, scale/recipe/test/diff/test_diff.py, scale/recipe/test/instance/json/test_recipe_v6.py, scale/recipe/test/instance/test_recipe.py, scale/recipe/test/messages/test_process_condition.py, scale/recipe/test/messages/test_purge_recipe.py
- data
- recipe
Completing recipe condition implementation
=> #1385 - Add conditions to v6 recipe definition JSON schema

Dockerfile, Dockerfile-dev, dockerfiles/examples/ace/Dockerfile, dockerfiles/examples/jpl-signatures/Dockerfile, dockerfiles/examples/landsat-base/Dockerfile, dockerfiles/examples/pca/Dockerfile, dockerfiles/examples/tad/Dockerfile, dockerfiles/framework/scale/entryPoint.sh, dockerfiles/framework/scale/scale.sudoers, scale/README.md, scale/docs/architecture/workspaces.rst, scale/mesos_api/tasks.py, scale/scale/local_settings_docker.py, scale/scale/settings.py, scale/scheduler/scale_scheduler.py
* scheduler
* settings
* All Mesos Docker Tasks are now launched as the `nobody` user.
* The Scale Webserver is now running as `nobody` user.
=> #1498 - Job improperly execute as root

scale/mesos_api/offers.py, scale/scheduler/resources/agent.py, scale/scheduler/resources/manager.py, scale/scheduler/resources/offer.py, scale/scheduler/scale_scheduler.py, scale/scheduler/scheduling/manager.py, scale/scheduler/test/scheduling/test_manager.py, scale/scheduler/test/scheduling/test_node.py, scale/scheduler/test/test_scheduler.py
- mesos_api
- scheduler
Decline all offers from mesos while we're paused.
Decline offers for a different role
Decline offers that have not been allocated when we're ready to launch tasks.
=> #1516 - Outstanding Scale offers in mesos

scale/diagnostic/views.py, scale/docs/rest/job_type.rst, scale/docs/rest/v6/ingest.rst, scale/docs/rest/v6/job.rst, scale/docs/rest/v6/job_type.rst, scale/docs/rest/v6/job_type.yml, scale/docs/rest/v6/queue.rst, scale/docs/rest/v6/scale_file.rst, scale/docs/rest/v6/scan.rst, scale/docs/rest/v6/strike.rst, scale/job/job_type_serializers.py, scale/job/views.py, scale/queue/serializers.py, scale/queue/views.py
- diagnostics
- job
- queue
Added the missing job type status endpoints to the v6 docs. Also added is_paused and unmet_resources to the job type base serializer to address #1528.  Updated references to job type base serializer across all docs.
=> #1527 - Add Missing Job Type Apis

scale/docs/rest/v6/error.rst, scale/docs/rest/v6/error.yml, scale/docs/rest/v6/ingest.yml, scale/error/models.py, scale/error/test/test_views.py, scale/error/test/utils.py, scale/error/views.py
- error
Fixed error rest api to actually do filtering like the api states it does. Also added filtering not mentioned to the docs.
=> #1524 - Fix Error Filtering

scale/data/data/json/data_v1.py, scale/data/test/data/json/test_data_v1.py, scale/job/models.py, scale/recipe/models.py
- data
- job
- recipe
Fix for converting single file directories from v6 to v1.
=> #1545 - Single File Directory

scale-ui/app/modules/charts/grid/gridChartController.js, scale-ui/app/modules/overview/partials/ovTemplate.html
Removed running icon and changed the grid title. Closes #1583
=> #1583 - Remove non-running job from job-grid on dashboard

scale/batch/test/test_views.py, scale/batch/views.py
- batch
Temporarily disabling batch creation until #1580 is fixed.
=> #1581 - Temporarily Disable Batches

scale/queue/models.py
- queue
We were trying to get the batch attribute for the queue manager instead of the job.
=> #1586 - Batch Job Priority Bug

scale/pip/requirements.txt
* Dependency update to resolve https://nvd.nist.gov/vuln/detail/CVE-2019-11324
=> Fix for CVE-2019-11324

web-docs/index.html
GitHub.io webpage
Just copied the image href on to the text so it links properly.
=> HOTFIX - added link ref to text

.gitlab-ci.yml, scale/docs/rest/v6/batch.yml, scale/docs/rest/v6/error.yml, scale/docs/rest/v6/ingest.yml, scale/docs/rest/v6/scale_file.yml
.gitlab-ci.yml
docs
Certain yaml files were causing `Invalid yaml file` errors when building on site. Mirroring all updates made to get the build to work.
=> :bookmark: #1615 Fixing invalid yaml issues

scale/docs/rest/v6/recipe_type.rst, scale/docs/rest/v6/recipe_type.yml, scale/recipe/models.py, scale/recipe/serializers.py, scale/recipe/test/test_views.py, scale/recipe/views.py
- recipe
Adding lists of job types and sub recipe types to recipe type list api.
=> #1526 - Recipe Gallery View Api Changes

scale/docs/rest/v6/error.rst, scale/docs/rest/v6/error.yml, scale/docs/rest/v6/ingest.rst, scale/docs/rest/v6/job.rst, scale/docs/rest/v6/job_type.rst, scale/docs/rest/v6/queue.rst, scale/docs/rest/v6/scale_file.rst, scale/docs/rest/v6/scan.rst, scale/docs/rest/v6/strike.rst, scale/error/fixtures/basic_errors.json, scale/error/migrations/0006_update_retried.py, scale/error/serializers.py, scale/ingest/fixtures/ingest_errors.json, scale/job/fixtures/basic_job_errors.json
- error
Updating selected system errors so they are automatically retried.
=> #1611 - Retry System Errors

scale/ingest/migrations/0017_populate_data_type_tags.py, scale/storage/migrations/0016_populate_data_type_tags.py
-ingest
-storage
Changing migrations to use sql queries for performance.
=> #1623 data type migration

dockerfiles/framework/scale/app-templates/silo.json, dockerfiles/framework/scale/app-templates/ui.json, dockerfiles/framework/scale/bootstrap.py, scale/README.md
Added Silo as a new default deployment as a Scale dependency. 2 new environment variables are now available:
* `SILO_DOCKER_IMAGE`: Image name used to deploy Silo during Scale boostrap.
* `SILO_ADDRESS`: Optional backend to use for Silo, will cause Silo to not be deployed during bootstrap. Scale UI will reverse proxy to this backend address to mitigate any CORS issues.
=> #1599: Deploy Silo with Scale

scale/docs/algorithm_integration/step4.rst
docs
Updating the algorithm integration documentation to reflect the recent changes to scale.  Also, it was 3 years old. 😬
=> Update also integration docs for new UI

.gitlab-ci.yml, build-support.sh
Updates made to ensure all updates to master trigger a build of Scale and supporting images for testing.
=> Docker all master

scale/job/migrations/0057_auto_20190603_1846.py
- job
Fixing the order of changed constraints.
=> #1682 - Fix alter index migration

scale/README.md, scale/scale/settings.py
N/A
Added toggle in webserver to deploy without authentication.
=> 1672 - Add authentication toggle

scale/job/execution/configuration/configurators.py
Job
Added runtime=nvidia to docker params for GPU jobs
=> added runtime=nvidia to docker params for gou jobs

.github/ISSUE_TEMPLATE/feature_request.md
=> typo fix in issue format

generate-release.sh, scale/scale/__init__.py, scale/scale/__init__.py.template
scale/scale init
Updated the version snapshot from 6.9.0 to 7.0.0
=> Version Update

tests/postman/environment.json, tests/postman/full-host-test.json
None, but should apply testing across the board
This change will ultimately lead to integration testing across the API by way of Postman (Newman) collections. The goal is to detect system level regressions that occur beyond the scope of an individual Scale unit tests.
The intention is for this to be used in the CI environment and in concert with the deployment testing documentation: 
https://github.com/ngageoint/scale/wiki/Deployment-testing
=> #1669: Initial host workspace test automation

dockerfiles/framework/scale/app-templates/ui.json, dockerfiles/framework/scale/bootstrap.py
Updated deployment to use `SILO_URL` and `API_URL` to communicate to the UI the addressable locations of the supporting APIs. This is to maintain consistency between components and eliminate confusion
=> #1709: Deployment consistency between UI and Scale variables

scale/docs/rest/v6/job.rst, scale/docs/rest/v6/job.yml, scale/docs/rest/v6/job_type.rst, scale/docs/rest/v6/job_type.yml, scale/job/job_type_serializers.py, scale/job/serializers.py, scale/job/test/test_views.py, scale/job/views.py, scale/recipe/test/test_views.py, scale/recipe/views.py
- job
Added max_tries field to rest api for job and job type.
=> #1697 - Show Job/Job Type Max Tries

build-support.sh
- n/a
Fixing support build script to properly name the image.
=> #1726 - Overwritten Support Images

scale/job/management/commands/scale_pre_steps.py
- Job
Modified what is constructed when building the input_metadata.
Old metadata `dict`: 
```
{
'JOB': {
'input_1': [
u'/path/to/some/file'
]
}
}
```
New metadata `dict`:
```
{  
'JOB':{  
'input_1':[  
{  
'has_been_published':False,
'data_ended':None,
'source_sensor':None,
'file_type':'SOURCE',
'file_name':'my_test_file.txt',
'unpublished':None,
'_state':<django.db.models.base.ModelState object at 0x10c5de2d0>,
'is_parsed':False,
'source_ended':None,
'source_collection':None,
'source_sensor_class':None,
'file_size':100            L,
'source_task':None,
'id':1,
'job_type_id':None,
'center_point':None,
'uuid':'',
'superseded':None,
'parsed':None,
'batch_id':None,
'media_type':'text/plain',
'file_path':'/file',
'workspace_id':1,
'deleted':None,
'job_exe_id':None,
'meta_data':{  
}, …
```
=> #1743 - Dump ScaleFile json to INPUT_METADATA json file

scale/recipe/messages/process_condition.py
recipe
Added verbose messages to log level INFO when evaluating conditions. The message prints out the evaluation result, the incoming data, and the condition to be evaluated.
=> Condition Evaluation Messages

scale/pip/production.txt, scale/pip/requirements.txt
=> Ensure we always use more-itertools less than 6 for Python 2.7 compat

scale/docs/rest/v6/ingest.yml, scale/ingest/models.py, scale/ingest/strike/configuration/json/configuration_v6.py, scale/ingest/test/test_views.py, scale/ingest/views.py, scale/storage/configuration/json/workspace_config_v6.py, scale/storage/models.py, scale/storage/test/test_views.py, scale/storage/views.py, scale/util/rest.py
- ingest
- storage
AWS credentials are masked in rest api functions unless being called by an admin
=> #1763 - secret credentials

scale/batch/messages/create_batch_recipes.py, scale/batch/test/messages/test_create_batch_recipes.py, scale/data/filter/filter.py, scale/data/test/filter/json/test_filter_v6.py, scale/data/test/filter/test_filter.py, scale/data/views.py, scale/docs/rest/v6/data.rst
- batch
- data
Fixed 'in' and 'not in' conditions to reflect expected behavior.  Also fixed a transient bug in batch creation (#1773) and a 504 error when creating dataset members (#1772)
=> #1760 - Review Data Filter Conditions

dockerfiles/framework/scale/bootstrap.py, scale/README.md, scale/scale/settings.py, scale/scheduler/dependencies/manager.py, scale/scheduler/test/dependencies/test_manager.py
- scheduler
Fix for status bugs in webserver.
=> #1789 - Dependency settings not passed to webserver

scale/job/migrations/0054_convert_manifest.py
- job
Fixing bugs found when migrating legacy job types
=> #1796 - Fix Job Type Manifest Migration

scale/docs/rest/v6/job.rst, scale/job/models.py, scale/job/serializers.py, scale/job/test/test_views.py
jobs
added configuration return to job details endpoint
=> #1798 - return priority with job details in API

dockerfiles/framework/scale/app-templates/ui.json, dockerfiles/framework/scale/app-templates/webserver.json
#1804: Fix for inability to hit APIs (Silo / Scale) from external domains due to lack of CORS header.
=> #1804: Simplify CORS down to single working response header

scale/job/messages/process_job_input.py, scale/job/test/messages/test_process_job_input.py, scale/recipe/definition/definition.py, scale/recipe/definition/node.py
job
when an input is missing, check to see if it was optional in the first place before throwing an exception.
=> 1806 - Scale Doesn't Handle Optional Output->Inputs

scale/ingest/test/test_models.py
ingest
added an extra test for edit_strike()
=> added a simple test for editing strike config through the model

scale/data/serializers.py, scale/data/test/test_views.py, scale/storage/serializers.py
data
adjusted serializer so dataset files now include country code in their list in the dataset details api endpoint
=> 1832 - Provide country codes with file list in datasets

scale/docs/rest/v6/scale_file.rst, scale/storage/models.py, scale/storage/test/test_views.py, scale/storage/views.py
Storage
Added countries as an extra option for filtering files
=> #1829- Add ability to filter files by country

scale/data/models.py, scale/data/serializers.py, scale/data/test/test_models.py, scale/data/test/test_views.py, scale/data/views.py, scale/docs/rest/v6/data.rst
data
Allow creation of dataset and dataset member in one call.
=> #1836 create datasets and members in one call

scale/data/models.py, scale/data/views.py, scale/recipe/models.py, scale/storage/models.py, scale/storage/test/test_views.py, scale/storage/views.py
Storage
Recipe
Data
Added created by filter for Scale Files and datasets.
=> Created filter

scale/batch/models.py, scale/data/models.py, scale/ingest/models.py, scale/ingest/test/triggers/test_ingest_recipe_handler.py, scale/job/models.py, scale/node/models.py, scale/recipe/models.py, scale/storage/models.py, scale/util/database.py
#1866 
Updated the ordering to apply case insensitive sorting to the charfield columns it could be ordered by. 
#1821
Added a specific ordering to the meta class of the recipe to default to order by title instead of index.
=> #1866 / #1821 Better alphabetical sorting

scale/data/views.py
Removes duplicated code causing multiple dataset records to be created.
=> Fixes Issue #1881

scale/ingest/ingest_job.py, scale/ingest/models.py, scale/ingest/scan/scanners/scanner.py, scale/ingest/strike/monitors/dir_monitor.py, scale/ingest/test/scan/scanners/test_s3_scanner.py, scale/job/configuration/data/job_data.py, scale/job/data/job_data.py, scale/job/execution/configuration/input_file.py, scale/source/models.py
ingest
#1885 
Updated the ingest (strikes and scans) to check for duplicate files by filename and file size instead of just filename.
I think this is ready - we might need some more testing with S3 strikes but from the code as far as I can tell we should be good.
=> #1885 Remove Unique Filenames requirement

scale/job/models.py
- [ x] `manage.py test` passes
scale.jobs.models
Jobs are now sortable by duration. #1867
=> #1867 - Add computed column for duration in jobs endpoint

Dockerfile, scale/docs/rest/v6/scale_file.rst, scale/pip/production.txt, scale/storage/models.py, scale/storage/views.py
Added ability to filter files by file_type. you can now choose to see only products or source files.
=> added file_type filtering and updated build

scale/data/models.py, scale/data/views.py
Added file_type to the dataset creation filter options.
=> added file_type to dataset creation filter

scale/ingest/fixtures/ingest_job_types.json, scale/scale/__init__.py, scale/scale/__init__.py.template
Updated default memory size of scan job to 1GB
=> Scanmemfix

scale/data/models.py, scale/data/views.py, scale/storage/models.py, scale/storage/views.py
=> Fix ScaleFile.objects.filter_files ingest time and mime type filters

scale/data/models.py, scale/data/views.py, scale/ingest/urls.py, scale/job/models.py, scale/job/views.py, scale/storage/models.py, scale/storage/views.py
=> PR Issue 1935 and Create Dataset ingest time filter fix
