scale/docs/interface/rest/job.rst, scale/docs/interface/rest/queue.rst, scale/job/models.py, scale/job/test/test_views.py, scale/job/views.py, scale/queue/test/test_views.py, scale/queue/urls.py, scale/queue/views.py, scale/util/rest.py, scale/util/test/test_rest.py
This adds a new endpoint: /queue/requeue-jobs/
The new API supports common filters by job attributes as well as the option to set a new job priority.
Filters that support multiple values are handled as true arrays, unlike our other endpoints because the view is based on POST instead of GET.
Existing /queue/requeue-job/ endpoint is still present, but is not deprecated until the UI updates.
=> Requeue multiple jobs

scale/docs/interface/rest/job.rst, scale/job/models.py, scale/job/serializers.py, scale/job/test/test_views.py, scale/job/test/utils.py
- Adds "inputs" and "outputs" top-level list attributes to the job details view.
- Each input or output consists of a name, type, and value. When a job has not yet run, the name and types of its inputs and outputs will always be defined, but the value may be null. A value can consist of primitives, a file, or an array of files. A file could be a basic scale file or a product file.
- Deprecates the "input_files" and "products" attributes for future removal.
- The serializer implementation is a bit of a hack because the value attribute can contain different types that must be handled dynamically.
=> Issue 70 Adding inputs/outputs to job details

scale/job/views.py, scale/scale/settings.py, scale/scale/urls.py, scale/util/rest.py
We decided to implement REST API versions using the URL prefix approach. DRF handles this by requiring a prefix for every URL pattern and declaring a namepsace for reverse lookups. Because every URL pattern must be updated, I created a utility method to automate it. This scheme is described here:
http://www.django-rest-framework.org/api-guide/versioning/#namespaceversioning
Therefore, to start a new version, we can simply add 'v4' to the settings file and all the existing APIs will be cloned to the new parent endpoint. Add that point, new serializer or view behavior can be implemented that inspect the requested version and take action accordingly using the request.version attribute.
- All existing endpoints should continue to work.
- All existing endpoints are now duplicated under the /v3 …
=> Added versioned URLs for REST API.

scale/ingest/migrations/0002_auto_20160414_0937.py, scale/ingest/models.py
This is a simple change to make the strike field non-nullable in the ingest model. This helps a number of other pieces of the code which expects the strike field to be populated.
This closes #155.
=> Issue 155 - Non-null Strike field

scale/job/configuration/interface/error_interface.py, scale/job/fixtures/basic_job_errors.json, scale/job/test/configuration/interface/test_error_interface.py, scale/job/test/execution/running/test_job_exe.py
This issue involved the creation of a default algorithm error that is reported for all job tasks that fail with a non-zero exit code that has no user-defined error mapped. This closes #124.
1. New error added to fixture
2. Small logic change in error mapping code
3. Added unit test
=> Issue 124 - Default Algorithm Error

scale/error/fixtures/basic_errors.json, scale/error/models.py, scale/job/management/commands/scale_post_steps.py, scale/job/management/commands/scale_pre_steps.py, scale/job/test/management/commands/test_scale_post_steps.py, scale/job/test/management/commands/test_scale_pre_steps.py
This issue looked at the pre and post task exit codes. This closes #130.
1. Created a new error to differentiate database and operational errors, which is the difference between database programming type issues and connection type issues.
2. Changed task exit codes to fit within 8 bits. Apparently Mesos only reports 8 bits worth of exit code, so the large exit codes were being truncated at the binary level and not matching the expected value in the scheduler.
=> Issue 130 - Fix pre and post exit codes

scale/docs/Makefile, scale/docs/architecture/django/index.rst, scale/docs/interface/rest/job.rst, scale/docs/interface/rest/job_execution.rst, scale/docs/interface/rest/queue.rst, scale/docs/make.bat, scale/job/models.py, scale/job/test/test_views.py, scale/job/views.py, scale/queue/test/test_views.py, scale/queue/views.py, scale/source/models.py, scale/util/command.py
- Confirmed that error model fields are already included in the jobs list view.
- Added an error_category filter to jobs view, jobs with executions view, and requeue view.
- Fixed some sphinx warnings.
Closes #156
=> Issue 156 - Add Error Information to Jobs API

scale/docs/interface/rest/error.rst, scale/docs/interface/rest/job_type.rst, scale/error/fixtures/basic_errors.json, scale/error/migrations/0003_error_is_builtin.py, scale/error/models.py, scale/error/serializers.py, scale/error/test/test_views.py, scale/error/test/utils.py, scale/job/clock.py, scale/job/fixtures/basic_job_errors.json, scale/metrics/apps.py, scale/metrics/daily_metrics.py, scale/metrics/migrations/0006_metricserror.py, scale/metrics/models.py, scale/metrics/serializers.py, scale/metrics/test/test_models.py, scale/metrics/test/utils.py, scale/scheduler/fixtures/scheduler_errors.json
- Added a new "is_builtin" field to the error model.
- Updated all errors created via fixtures to be flagged as built-in.
- Added new field to REST services/docs.
- Created a new errors daily metrics table that counts these error types based on job executions.
NOTE: Although there is a migration to add the new field, it will default all existing records to false. Production systems will need to manually change the value to true where applicable.
Closes #158
=> Issue 158 - Builtin Error Metrics

scale/docs/rest/source_file.rst, scale/product/test/utils.py, scale/source/models.py, scale/source/serializers_extra.py, scale/source/test/test_views.py, scale/source/urls.py, scale/source/views.py
- Added a new endpoint /sources/X/, where X can be either a model id or a file name.
- Response includes the source model details and lists of its associated ingests and products.
- Implementation was a bit awkward to workaround circular dependency issues with higher-level models.
Closes #99
=> Issue 99 - Source File Detail API

scale/docs/rest/queue.rst, scale/job/models.py, scale/queue/models.py, scale/queue/serializers.py, scale/queue/test/test_views.py, scale/queue/views.py
- Refactored the queue status view to follow REST guidelines.
- The refactor adds the missing icon_code field available, as well as the other base job type fields.
- Left the original response structure in place as well for backward compatibility.
- Also added just the icon_code field to the original structure so that it can be optionally used without the UI needing to refactor immediately if desired.
=> Issue 202 - Refactored queue status view to follow REST guidelines.

dockerfiles/framework/scale/Dockerfile
I changed the Dockerfile to open up the permissions to 777 on the /scale/output_data so that algorithm job containers can run as any users and have appropriate access to write output files.
=> Issue 229 PR - Opening up permissions on output_data directory

scale-ui/app/modules/jobs/directives/jobHealthDirective.js
Increased the page size for now to address the job status part of issue #316.  This will only work until there are >1000 job types, so more work needs to be done in order to arrive at a more permanent solution.  For now though this should be merged in to fix a bug that's hindering users on-site.
=> Issue #316 - Accommodate larger amount of job types on Overview page

scale/port/views.py
- Removed default parsers so only a multi-part form post is accepted.
- Added a custom renderer so the default HTML form is not displayed.
- Added a more detailed description to explain the purpose of the view that is displayed in the browseable API.
=> Issue 326 - Restrict configuration import upload view

scale/docs/architecture/workspaces.rst, scale/pip/build_linux.txt, scale/pip/dev_win.txt, scale/pip/prod_linux.txt, scale/product/models.py, scale/product/test/test_models.py, scale/source/models.py, scale/storage/apps.py, scale/storage/brokers/broker.py, scale/storage/brokers/factory.py, scale/storage/brokers/host_broker.py, scale/storage/brokers/nfs_broker.py, scale/storage/brokers/s3_broker.py, scale/storage/configuration/workspace_configuration.py, scale/storage/exceptions.py, scale/storage/management/commands/scale_delete_file.py, scale/storage/management/commands/scale_download_file.py, scale/storage/management/commands/scale_move_file.py, scale/storage/management/commands/scale_upload_file.py, scale/storage/models.py, scale/storage/settings.py, scale/storage/test/brokers/test_host_broker.py, scale/storage/test/brokers/test_nfs_broker.py, scale/storage/test/brokers/test_s3_broker.py, scale/storage/test/test_models.py, scale/storage/test/utils.py
- Adds an initial implementation of the S3 storage system broker.
- Supports standard delete, download, move, and upload.
- S3 does not support an atomic move, so that must be implemented as a copy + delete.
- S3 operations can momentarily fail or timeout, so this broker includes support for a few retry attempts.
- Currently, requires AWS credentials to be hard-coded into the workspace JSON config in plain text. A future issue will need to change this to an encrypted store of some kind.
- Added management commands to make it easy to test broker implementations without running all of scale.
- Refactored how broker implementations are registered to avoid circular dependency problems.
- It looks like file models are not updated on a delete the way other operations were, so I added that to …
=> Issue 18 - AWS S3 broker

dockerfiles/framework/scale/entryPoint.sh, dockerfiles/framework/scale/scale.conf
Trevor, i have added the sudo's and removed the PREFIX. running it off of root appears to work. Also i figured out the problem we had yesterday when we left. it was due to the scale user (7498) not being present on the slaves. it appear mesos was trying to chown something to "scale" and we didn't have a scale user on devnet. this could be an issue in the future with people testing out scale in their environments.
=> Issue 180 - Docker image updates

scale/job/execution/running/tasks/base_task.py, scale/job/execution/running/tasks/job_task.py, scale/job/execution/running/tasks/post_task.py, scale/job/execution/running/tasks/pre_task.py, scale/job/test/execution/running/test_job_exe.py
Right now we expect there to not be an exit code when a task launch fails. It appears that Mesos is now returning an exit code of 1 when a task launch fails.
Remove the requirement for no exit code when detecting a task launch. Basically remove
> and not task_results.exit_code:
from line 184 of base_task.py and update applicable unit tests.
Make sure that task launch errors are triggered even when an exit code is returned.
I also had to add checks to make sure the task started running before looking at the exit code to determine the error.
=> Issue 355 - Fix Task Launch Detection

scale/pip/build_linux.txt, scale/pip/dev_win.txt, scale/pip/prod_linux.txt, scale/storage/brokers/s3_broker.py, scale/storage/settings.py, scale/storage/test/brokers/test_s3_broker.py
This version should now work with any configuration method supported by boto3, such as the EC2 IAM role, AWS credentials file, AWS config file, or environment variables. The existing solution to have hard-coded credentials in the workspace config should also continue to work for ease of testing.
See here for more information:
http://boto3.readthedocs.io/en/latest/guide/configuration.html
I'm not sure if this code will work for custom boto3 builds on other networks yet.
=> Issue 364 - Upgrade S3 broker to use boto3

scale-ui/app/modules/feed/partials/ingestRecordsTemplate.html, scale-ui/app/modules/jobs/partials/jobTypesFailureRatesTemplate.html, scale-ui/app/modules/jobs/partials/jobsTemplate.html, scale-ui/app/modules/load/partials/loadTemplate.html, scale-ui/app/modules/load/partials/queueRunningTemplate.html, scale-ui/app/modules/recipes/partials/recipesTemplate.html, scale-ui/app/test/scripts/backendStubs.js
Removed the `ng-if="vm.gridOptions.data.length > 0"` statement from all grids.  That was originally there to ensure that they render properly without internal scrollbars, but from my testing it seems as though it's not required to accomplish this.  So when reviewing this PR, just ensure that all the grid rows render as expected, without internal scrollbars, and that page scrolling is not adversely affected in any way.
Both the Jobs and Ingests grids will filter on status when running the static build.
Fixes #376
=> Issue #376 - Datagrids disappear when no data is returned

scale/docs/rest/job.rst, scale/docs/rest/queue.rst, scale/docs/rest/recipe.rst, scale/job/models.py, scale/job/serializers.py, scale/job/test/test_views.py, scale/job/test/utils.py
Implemented according to the original issue, except root_superseded_job_id and superseded_job_id fields are replaced with nested objects per the standard REST conventions.
=> Issue 58 - Add Superseded Info to Job Detail API

scale/docs/rest/recipe.rst, scale/queue/models.py, scale/recipe/handlers/graph.py, scale/recipe/handlers/handler.py, scale/recipe/models.py, scale/recipe/serializers.py, scale/recipe/test/handlers/test_handler.py, scale/recipe/test/test_models.py, scale/recipe/test/test_views.py, scale/recipe/test/utils.py, scale/trigger/handler.py
Implemented according to the original issue, except root_superseded_recipe_id and superseded_recipe_id fields are replaced with nested objects per the standard REST conventions. Also used the RecipeBaseSerializer with a bit of added info to be consistent with the jobs API.
Made a couple small changes to the recipe handler API to make it more general for additional use cases and included some minor formatting/warning cleanup.
=> Issue 59 - Add Superseded Info to Recipe Detail API

scale/docs/rest/job.rst, scale/docs/rest/job_execution.rst, scale/docs/rest/node.rst, scale/job/models.py, scale/job/views.py, scale/queue/views.py
Updated all REST views that have a status filter related to jobs. Only exception was the job re-queue API because it is a potentially breaking change due to it being packaged as a JSON POST rather than query string parameters.
=> Issue 161 - Update job views to support filtering by multiple status values

scale/docs/rest/ingest.rst, scale/ingest/models.py, scale/ingest/test/test_views.py, scale/ingest/views.py
Added strike_id filter parameter to ingests view that accepts multiple values.
Updated status filter to accept multiple values.
=> Issue 321 - Filter Ingest REST API by Strike

scale/job/configuration/interface/error_interface.py, scale/job/execution/running/tasks/job_task.py, scale/job/test/configuration/interface/test_error_interface.py
Changed job task to provide a default 'unknown' error when a system job fails instead of defaulting to 'algorithm-unknown' error for everything.
=> Issue 188 - General algorithm error should not be used on system jobs

scale/docs/algorithm_integration/step2.rst
This is a simple documentation update that explains that output files and results manifest files created by algorithms need to have full read permission open so that the post task can read them.
=> Issue 268 - Open Read Permissions on Output Files

scale/mesos_api/tasks.py, scale/mesos_api/utils.py, scale/pip/dev_win.txt, scale/scheduler/management/commands/scale_scheduler.py, scale/scheduler/scale_scheduler.py, scale/scheduler/threads/db_sync.py, scale/scheduler/threads/recon.py, scale/scheduler/threads/schedule.py
Added a new requirement for mesos.interface in the dev_win.txt file. 
Moved the import from mesos.interface out of the try catch block and removed the try catch block in all occurrences of mesos.interface imports
=> Issue 391 - Mesos.interface could not be imported for new development environments

scale/docs/architecture/jobs/index.rst, scale/docs/architecture/jobs/job_configuration.rst, scale/job/models.py
I added documentation on the job configuration schema that was added as part of the Scale Dockerization.
I did not remove the job_environment field on the job_execution model since this would impact the REST API and UI. It can be removed in the future with other job_execution changes.
=> Issue 218 - Job Configuration Documentation

scale/mesos_api/tasks.py, scale/mesos_api/utils.py, scale/pip/dev_win.txt, scale/scheduler/management/commands/scale_scheduler.py, scale/scheduler/scale_scheduler.py, scale/scheduler/threads/db_sync.py, scale/scheduler/threads/recon.py, scale/scheduler/threads/schedule.py
Added mesos.interface to the list of requirements in dev_win.txt
Moved the mesos.interface imports out of the try/catch block in all occurrences, no longer falling back on stubs
=> Issue 391 - Mesos.interface errored on import for new development environments

scale/job/execution/running/tasks/base_task.py, scale/scale/__init__.py, scale/scale/__init__.py.template, scale/scale/settings.py
I created a new Django setting to contain the version tag used to tag the Scale Docker image. This centralizes the logic for replacing the '+' with an '_'.
=> Issue 419 - Docker Image Version Tag

scale/job/models.py, scale/job/test/test_models.py, scale/job/test/test_views.py
Modified the IF statement that was throwing an exception if a system job was attempted to be modified. Now instead of always throwing an exception for an attempted edit on a system job, an exception is only thrown if a field other than 'is_paused' is attempted to be edited.
Also added a unit test to verify this
=> Can now edit 'is_paused' field for a system job

scale-ui/app/modules/overview/partials/ovTemplate.html, scale-ui/app/styles/pages/overview.less
Removed a legacy css class that was causing a gap to appear on the overview page.
=> Overview margin fix

scale-ui/app/modules/jobs/controllers/jobDetailController.js, scale-ui/app/modules/jobs/controllers/jobsController.js, scale-ui/app/modules/jobs/directives/jobExecutionLogDirective.js, scale-ui/app/modules/jobs/directives/jobExecutionLogTemplate.html, scale-ui/app/test/data/job-details/jobDetails10.json, scale-ui/app/test/data/jobs.json
This is a fix to display execution error details in the log viewer header.
Updated execution log viewer to use Execution details that have already been loaded. These details used to come from log service, but not since the changes were made to support elasticSearch logging. The data is already on $scope so no additional data loads were necessary.
=> Log Viewer Fix

scale/mesos_api/tasks.py
This is a bug fix that checks that the settings.CONFIG_URI is set from the environment variable before setting it to the Mesos task uris field.
=> Issue 456 - Bug with CONFIG_URI set to None

scale/queue/models.py, scale/queue/test/test_models.py, scale/queue/views.py, scale/recipe/models.py, scale/recipe/test/test_models.py, scale/recipe/test/utils.py
- Changed create_recipe call to queue_recipe so that jobs are scheduled.
- Fixed create_recipe parameter order to be consistent with other APIs.
- Fixed queue_recipe to return a recipe handler to be consistent with other APIs.
- Added unit test asserts to cover the bug.
=> Issue 457 - Fixed reprocessed recipes to also queue up jobs.

scale/docs/rest/source_file.rst, scale/source/models.py, scale/source/serializers_extra.py, scale/source/test/test_views.py, scale/source/views.py
- Added superseded field to products in the sources details view.
- Excluded superseded products by default.
- Added parameter to include superseded products.
- Updated tests and docs.
=> Issue 483 - Add product superseded fields to sources REST API

scale/docs/rest/job.rst, scale/job/models.py, scale/job/test/test_views.py, scale/job/test/utils.py, scale/job/views.py
- Updated get_jobs to exclude superseded jobs by default.
- Added supersedes parameters to jobs, job updates, and jobs with executions views.
- Updated tests and docs.
=> Issue 497 - Add superseded filter to jobs API

scale/queue/test/test_views.py, scale/queue/views.py
I was unable to reproduce the error, so I had to take a guess that it might be the problem we've seen in the past where there was no queryset attribute defined on the REST API view. It would be good if a quick test could be done to verify the fix in production.
The corresponding unit test was not very representative of real usage, so I did take the time to flesh it out better and attempted to improve error messages.
=> Issue 508 - Queue New Job API returns 500 error

scale/docs/rest/queue.rst, scale/queue/serializers.py, scale/queue/test/test_views.py, scale/queue/views.py
- Fixed the DRF HTML form to show example JSON with the correct fields.
- Updated the docs for the POST endpoint to show a valid example.
- Changed view to return a 200 response when no jobs match the query.
Not fixed as part of this PR:
- View hangs for large queries (we already have a separate issue covering that).
- Requeue All button grabs more than what is selected. Not sure exactly what this means, but it sounds like a UI bug.
=> Issue 532 - Requeue Job API Broken

scale-ui/app/modules/recipes/directives/recipeGraphViewerDirective.js, scale-ui/gulpfile.js, scale-ui/package.json
Fixes #511. Updated Recipe Editor to allow saving when there are validation warnings. API returns HTTP errors when there are validation errors and save is not allowed.
=> Issue 511 - Recipe editor validation warnings no longer prevent save

scale/batch/management/commands/scale_batch_creator.py, scale/batch/test/management/commands/test_scale_batch_creator.py
The unit test did not verify the arguments were correct, only that a method was called so the new command never actually worked in practice.
=> Issue 603 - Fixed executing batch creator command

scale-ui/app/modules/jobs/partials/jobTypesTemplate.html
Removed `{{vm.jobTypesParams.show_rd}}` from job type title.  Fixes #602
=> Issue 602 - job types true/false

scale/batch/configuration/definition/batch_definition.py, scale/batch/test/configuration/definition/test_batch_definition.py, scale/batch/test/test_models.py, scale/util/parse.py, scale/util/rest.py, scale/util/test/test_parse.py
- Removed regex pattern for validating date formats with json schema and instead use our built-in parsing so the validation is more robust.
- Updated unit tests to use full time stamps.
- Changed parse util to use a more standard ValueError instead of a custom ParseError to make caller code simpler.
=> Issue 603 - Fixed batch to accept full time stamps

scale/docs/rest/job_type.rst, scale/job/models.py, scale/job/test/test_views.py, scale/job/test/utils.py, scale/job/views.py
- Updated /job-types/ API to only include active job types by default.
- Added a new is_active filter parameter.
- Updated tests and docs.
=> Issue 604 - Need the ability to filter out inactive jobs

scale-ui/app/modules/common/services/stateService.js, scale-ui/app/modules/jobs/controllers/jobTypesFailureRatesController.js, scale-ui/app/modules/jobs/partials/jobTypesFailureRatesTemplate.html
Closes #567 
Clicking on each of the error type headers in any of the columns will sort the data by that error type over the associated time period.  Clicking on "Failure %" will sort the data by failure percentage.  Default sort is desc, but clicking on each header multiple times will toggle between asc and desc. A directional caret icon is displayed next to the label currently being used for sorting.
Right now this sorting is not persisted through the URL. Please comment if that is necessary.
=> Issue 567 - Add ability to sort Failure Rates list by failure type

scale/ingest/strike/monitors/s3_monitor.py
Update to support reloading Strike configuration following each pass over the SQS. If there is a message backlog, all messages will be processed before the configuration is reloaded.
=> #617: Reload configuration of S3 monitor during live strike execution.

Dockerfile, dockerfiles/framework/scale/bootstrap.py, dockerfiles/framework/scale/entryPoint.sh, dockerfiles/framework/scale/gunicorn.conf.py, dockerfiles/framework/scale/scale.conf, scale-ui/config/scaleConfig.json, scale/pip/prod_linux.txt, scale/scale/local_settings_docker.py, scale/scale/settings.py, scale/scale/wsgi.py, scale/scheduler/management/commands/scale_scheduler.py, scale/util/middleware.py
Django uses WSGI SCRIPT_NAME environment values to identify what the context it is running within. Optimally, we would have 2 contexts configured (/service/scale/api and /api). The first would support DCOS Admin UI and the 2nd Marathon LB. Unfortunately, there is no way to get DCOS Admin to reverse proxy to the /service/scale endpoint as it is explicltly set to only proxy to the root context.
The workaround is to set the default behavior of Scale webserver to operate at `/scale/service/api` and use a header injected by Marathon LB (haProxy) to tell the Scale WSGI connector to operate at `/api`. This logic can be found in `scale/wsgi.py`
This pull request also removes gunicorn, as configuration of WSGI environments is significantly complicated when there is a second reverse proxy in front …
=> #569: Correct Django SCRIPT_NAME behind DCOS and Marathon LB

scale/ingest/strike/monitors/s3_monitor.py
- Lowered to debug level the log message indicating SQS poll.
- Warning message added when unrecognized messages are discarded.
=> #616: Logging updates for SQS monitoring

scale/job/models.py
Fix to use exact (not-analyzed) raw strings for execution ID and output type for log retrieval
=> #633: Fix for matching all logs 

Dockerfile, dockerfiles/logstash-elastic-ha/Dockerfile, generate-release.sh
Added labels to both main Scale and Logstash HA images to satisfy the requirements outlined in #630. As updates were also needed to `generate-release.sh` to accomodate, fixes were applied there to address #576. There were typos referencing the version environment variable and a missing push to apply the snapshot version to the Python environment.
=> #630 and #576: Docker labels and release updates.

scale/storage/brokers/s3_broker.py, scale/storage/test/brokers/test_s3_broker.py, scale/util/aws.py, scale/util/test/test_aws.py
Handling for a number of whitespace filled values provided via UI. host_path, credentials.access_key_id and credentials.secret_access_key now all will probably be handled when only containing whitespace.
=> #615 - S3 strike and broker configuration hardening

scale/job/execution/running/tasks/cleanup_task.py, scale/scheduler/cleanup/node.py
Dead containers are now cleaned up.
Also cleanup tasks are only created when the tasks are ready to be scheduled.
=> Issue 642 - Cleanup dead containers

scale/ingest/migrations/0006_auto_20161202_1621.py, scale/ingest/migrations/0007_auto_20161206_1329.py, scale/ingest/models.py, scale/ingest/test/utils.py, scale/source/models.py, scale/source/test/test_models.py, scale/storage/migrations/0003_auto_20161202_1621.py, scale/storage/models.py
Created data_started and data_ended fields for the ingest model that are copied from the corresponding source file when it is parsed.
Added appropriate indexes for the way the ingest models are accessed (ingest_ended, data_started, data_ended).
Re-worked the API query to cut out joining the source_file, scale_file, and workspace models.
Added migration to populate existing ingest models with their source_file's data time.
=> Issue 637 - Fix Ingest Status REST API Slowness

scale/job/configuration/data/job_data.py, scale/product/models.py, scale/product/test/test_models.py
This PR updates the product UUID calculation to include property inputs. This ensures that property inputs are taken into consideration when Scale is determining whether a job is running on the "same data" as before or not.
=> Issue 685 - Make property inputs affect UUID

scale/storage/brokers/s3_broker.py
Added additional except case to catch S3 credentials that are missing from the workspace.
=> S3 bucket validation should catch credential errors

Dockerfile
- Added ability to control whether EPEL is installed. This supports alternative offline base images that could already have EPEL configured to a non-default location.
- Updated description of Docker image to match repo.
=> #676 - Make EPEL install optional during Docker build

scale/ingest/apps.py, scale/ingest/fixtures/ingest_errors.json, scale/ingest/test/test_app.py, scale/job/execution/tasks/job_task.py, scale/job/fixtures/basic_job_errors.json, scale/job/tasks/base_task.py, scale/job/test/execution/test_job_exe.py
Set up system jobs to have SYSTEM errors when they time out, including the option to have an error specific to the job type. For example, there is an error specifically for ingest time outs to give a specific, useful error description to the user.
=> Issue 632 - System Timeout Errors

scale/job/configuration/data/job_data.py, scale/job/models.py, scale/job/test/test_models.py
I fixed the handling of job_data to not break when extra inputs exist in the job_data that aren't defined in the job type interface.
1. Updated job_data validation to warn about extra, unknown inputs and strips them out of the job_data that gets saved in the database.
2. Updated JobManager._merge_job_data() to ignore inputs in the job data that are not in the interface. This will prevent jobs with extra inputs from breaking the job details REST API call.
=> Issue 666 - Fix job_data bug

scale/job/execution/tasks/cleanup_task.py, scale/job/execution/tasks/exe_task.py, scale/job/execution/tasks/job_task.py, scale/job/execution/tasks/post_task.py, scale/job/execution/tasks/pre_task.py, scale/job/tasks/base_task.py, scale/job/tasks/pull_task.py, scale/mesos_api/tasks.py, scale/scheduler/cleanup/node.py, scale/scheduler/node/manager.py, scale/scheduler/node/node_class.py, scale/scheduler/scale_scheduler.py, scale/scheduler/test/node/test_manager.py, scale/scheduler/test/node/test_node_class.py, scale/scheduler/test/offer/test_manager.py, scale/scheduler/test/offer/test_node.py, scale/scheduler/test/threads/test_schedule.py, scale/scheduler/threads/schedule.py, scale/scheduler/threads/task_handling.py
This PR updates the nodes so that they each pull the Scale Docker image upon registering with Scale (after initial cleanup). This ensures that a node has the Scale Docker image before it runs any jobs. The forcePull Docker flag is now turned off for all tasks that run the Scale Docker image (all system jobs and pre and post tasks).
=> Issue 614 - Pull Scale Docker image

scale/job/configuration/configuration/job_configuration.py, scale/job/configuration/interface/exceptions.py, scale/job/configuration/interface/job_type_configuration.py, scale/job/test/configuration/interface/test_configuration_interface.py
Added validation to job type configuration to ensure that settings values are always strings.
Also added automatic string conversion when settings are added to a job configuration.
=> Issue 722 - Settings bug fix

scale/docs/rest/source_file.rst, scale/product/models.py, scale/product/test/utils.py, scale/source/models.py, scale/source/test/test_models.py, scale/source/test/test_views.py, scale/source/urls.py, scale/source/views.py
Created a new REST API to retrieve the products generated from a given source file, with the ability to filter by batch, along with other product field filtering.
/sources/{source-id}/products/?batch_id={batch-id} (along with other product field filtering)
=> Issue 729 - REST API for source products

scale/docs/rest/source_file.rst, scale/job/models.py, scale/product/migrations/0009_auto_20170301_1130.py, scale/product/models.py, scale/source/models.py, scale/source/test/test_models.py, scale/source/test/test_views.py, scale/source/urls.py, scale/source/views.py
This PR adds a REST API call to retrieve the jobs associated with a source file. It includes all standard filtering query parameters available on the normal /jobs/ API.
URL: /sources/{source-id}/jobs/
=> Issue 740 - Source Jobs REST API

scale/batch/configuration/definition/batch_definition.py, scale/batch/models.py, scale/batch/test/configuration/definition/test_batch_definition.py, scale/batch/test/test_models.py, scale/batch/test/test_views.py, scale/batch/views.py, scale/docs/architecture/jobs/batch_definition.rst, scale/docs/rest/batch.rst, scale/storage/test/utils.py
- Updated batch definition to support trigger rules for existing files using either the recipe types's default rule or a completely custom rule.
- Trigger rule implementation is modeled after the existing ingest triggers.
- Updated batch processor, REST views create/validate, tests, and docs to support the new definition.
=> Issue 585 - Batch trigger files for recipes

scale/job/models.py, scale/product/models.py
This PR has some quick performance improvements to queries by using select_related() and defer().
This is obviously not the best solution; in a future issue the base serializer that only renders an ID will be changed so it doesn't require a elated model to be fetched.
=> Issue 754 - Performance improvements to queries

scale/queue/models.py
Switched queue logic to use LIFO instead of FIFO as secondary sorting measure
=> Issue 758 - Switched queue logic to use LIFO instead of FIFO

scale-ui/app/modules/common/services/scaleService.js, scale-ui/app/modules/metrics/controllers/metricsController.js, scale-ui/app/styles/main.less, scale-ui/app/styles/pages/metrics.less
Fixes #757
Added formatters to account for months and years.  Years, months, and days are labeled with capital letters, while hours, minutes, and seconds are labeled with lower-case letters.
This was not a bug confined to the metrics page, as the same duration formatter is used to display durations in data grids.
=> Issue 757 - Metrics Page Total Cut Off

scale/job/execution/job_exe.py, scale/job/models.py, scale/queue/models.py, scale/queue/test/test_models.py
This PR improves the scheduler so that if one or more job executions have bad configuration that prevent them from being scheduled, the rest of the scheduling is not affected.
=> Issue 774 - Better handling of bad job exe configuration

scale-ui/app/modules/feed/controllers/ingestRecordsController.js, scale-ui/app/modules/feed/partials/ingestRecordsTemplate.html
This field was already debounced, and to increase the delay didn't seem like it would solve the problem.  As a result I added a button that can be used to apply the filename filter when the user is ready.  Pressing the "enter" key will also apply the filter.
=> Issue 767 - Debounce filename search for ingest records

scale/ingest/migrations/0013_auto_20170406_1517.py, scale/ingest/models.py
I changed the description fields for Strike and Scan to be text fields that allow nulls. This is consistent with other models (e.g. job type).
=> Issue 765 - Create Strike API fails without description

scale/scheduler/node/manager.py, scale/scheduler/node/node_class.py, scale/scheduler/test/node/test_manager.py
This PR improves the scheduler's handling of nodes.
1. If a node model has its hostname renamed in the database (not a supported feature), the scheduler now logs an error message of throwing an exception and halting progress of the background thread.
2. If a node is both inactive and offline, the scheduler removes the node from its in-memory data structures. There is no point in the scheduler keeping the node around and it will prevent memory growing over time due to accruing data from nodes that are no longer used.
=> Issue 775 - Improve scheduler resilience with handling nodes

scale-ui/app/modules/app.js, scale-ui/app/modules/common/services/stateService.js, scale-ui/app/modules/feed/controllers/scanDetailsController.js, scale-ui/app/modules/feed/controllers/scansController.js, scale-ui/app/modules/feed/models/Scan.js, scale-ui/app/modules/feed/models/ScanConfiguration.js, scale-ui/app/modules/feed/models/ScanIngestFile.js, scale-ui/app/modules/feed/partials/scanDetailsTemplate.html, scale-ui/app/modules/feed/partials/scansTemplate.html, scale-ui/app/modules/feed/services/scanService.js, scale-ui/app/test/data/scans.json, scale-ui/app/test/data/scans/scan1.json, scale-ui/app/test/data/scans/scan2.json, scale-ui/app/test/scripts/backendStubs.js, scale-ui/config/scaleConfig.json
Closes #815.
There may yet be some changes that need to be made, since I wasn't entirely sure which fields were of interest to users both in the grid and detail views.  The "File Count" and "Job" values are null in the grid screenshots below because that's what's being returned by the API - probably because our Scale instance over here is pretty bare.  But that might be good to verify.
I also pulled in the reordering changes from #688 so this has the same functionality as strikes.
=> Issue 815 - Create UI for scan ingests

scale/scheduler/node/conditions.py, scale/scheduler/scale_scheduler.py, scale/scheduler/test/node/test_node_class.py
Created a node error for a general health check error. Right now a node error is only applied if the exit code is parsed and matches a known exit code error condition.
=> Issue 825 - General health check failure

README.md, dockerfiles/vault-dcos/Dockerfile, dockerfiles/vault-dcos/Readme.md, dockerfiles/vault-dcos/config.hcl
*  Corrected mistake in scale README.md in docker env_vars table
* Updated Vault version to recent stable release
* Updated vault-dcos README.md with:
* Updated workflow to match DC/OS 1.8.8
* Unified service name (scale-vaule) and references throughout
* Transitioned heath check to COMMAND, using cURL
* Added section about vault back end management with ZooKeeper.
=> #810 - Update dcos-vault to include proper health checks

scale/README.md, scale/job/configuration/json/execution/exe_config_1_0.py
This is a backwards incompatible change and should NOT be merged until after the 4.4.0 release.
Until this is merged in, we do not support Docker engine v1.11 or newer on cluster nodes running Scale jobs. Jobs will run and execute to completion, but the format of the syslog messages sent to logstash will be invalid, rendering all logging APIs useless.
=> #790: Docker 1.11+ logging fix.

dockerfiles/framework/scale/bootstrap.py
Deployment of the RabbitMQ service into Marathon via the Scale bootstrap. This will only be deployed when the `SCALE_BROKER_URL` environment variable is _unset_. This behavior mirrors that of the database and logstash deploys. The RabbitMQ Marathon app is also treated exactly like the Postgres app as it is a persistent store of data.
I also reworked how the apps are launched to parallelize the deployment of all apps that are independent of each other (scale-db, scale-rabbitmq, scale-logstash). The only app blocking during the deployment process is the webserver as it needs to know the ports / addresses of the other running services. This should reduce the start up time to roughly 1/3rd of that previously experienced.
=> RabbitMQ deploy

dockerfiles/framework/scale/bootstrap.py, dockerfiles/framework/scale/entryPoint.sh, scale/environment/cent7-init.sh, scale/environment/cloud-init.sh, scale/environment/mac-init.sh, scale/environment/win-init.bat, scale/scale/local_settings_dev.py, scale/scale/local_settings_docker.py, scale/scale/settings.py
Added passthrough of SCALE_BROKER_URL from bootstrap into the Scale application. This is used internally to the messaging components. 
Also updated the developer bootsrap scripts for all environments to configure RabbitMQ for local and cloud IDE development.
=> Broker URL passthrough and developer bootstrap

scale/job/execution/job_exe.py, scale/job/execution/tasks/cleanup_task.py, scale/job/execution/tasks/exe_task.py, scale/job/execution/tasks/job_task.py, scale/job/execution/tasks/post_task.py, scale/job/execution/tasks/pre_task.py, scale/job/execution/tasks/pull_task.py, scale/job/fixtures/basic_job_errors.json, scale/job/models.py, scale/job/tasks/base_task.py, scale/job/tasks/health_task.py, scale/job/tasks/manager.py, scale/job/tasks/pull_task.py, scale/job/test/execution/test_job_exe.py, scale/mesos_api/tasks.py, scale/scheduler/recon/manager.py, scale/scheduler/scale_scheduler.py, scale/scheduler/sync/job_type_manager.py, scale/scheduler/threads/recon.py, scale/scheduler/threads/task_handling.py
Added an initial pull task to job executions so that image pulling does not occur during task staging. Turned off forcePull and tightened the limits of staging reconciliation/timeouts. Also added a check for pulling the Scale image where the registry is not hit if the image has already been pulled.
=> Issue 880 - Pull task for job executions

scale/product/models.py
the job_output for the Product model was only being assigned if part of a recipe.  I moved the assignment outside that if-statement block to a more appropriate location.
=> Moved job_output assignment to better location

scale-ui/app/modules/recipes/controllers/recipeDetailsController.js, scale-ui/app/modules/recipes/models/RecipeDetails.js, scale-ui/app/test/data/recipe-details/recipeDetail1.json, scale-ui/app/test/data/recipe-details/recipeDetail2.json, scale-ui/app/test/data/recipe-details/recipeDetail3.json, scale-ui/app/test/data/recipe-details/recipeDetail4.json, scale-ui/app/test/data/recipe-details/recipeDetail5.json, scale-ui/app/test/data/recipe-details/recipeDetail6.json
Fixes #894 
The call to get the recipe type detail has been left in, and the resulting definition is being replaced with the revision definition. This was necessary due to the fact that job type data essential for the recipe viewer is not included in the recipe details response. So if the recipe type details call was not made, additional calls (potentially multiple) would have needed to be made further down the line to get the appropriate job type data.
=> Issue 894 - Recipe detail bug

dockerfiles/framework/scale/bootstrap.py, scale/docs/rest/job_type.rst, scale/docs/rest/port.rst, scale/job/configuration/interface/job_interface.py, scale/job/configuration/json/job/job_config.py, scale/job/models.py, scale/job/serializers.py, scale/job/test/test_views.py, scale/job/views.py, scale/port/exporter.py, scale/port/importer.py, scale/port/serializers.py, scale/port/test/test_views.py, scale/scale/local_settings_docker.py, scale/scheduler/vault/manager.py, scale/vault/exceptions.py, scale/vault/secrets_handler.py, scale/vault/test/test_secrets_handler.py
1. Add `configuration` support to the following API endpoints:
- GET `/job-types/{id}/`
- POST `/job-types/validation/`
- PATCH `/job-types/{id}/`
- POST `/configuration/`
- GET `/configuration/`
- POST `/configuration/validation/` 
- POST `/configuration/`
2. Updated `Vault` app - Added error to for when no secrets backend is configured but someone submits a secret to Scale.
3. Added two functions to job_config: `get_secret_settings` and `validate` - The first gathers the secrets before sending to `Vault` and the last checks for secrets and unused settings, as well as unused mounts, and discards them. 
4. Added function to JobType that will send secrets off to `Vault` 
**I will deploy this in our test_env to ensure it works with Vault.**
=> #816 - Update REST API for settings secrets

scale/job/configuration/interface/job_interface.py, scale/job/models.py, scale/job/test/configuration/interface/test_job_interface.py
* Centralized the generation of the job_type secrets key for use with Vault or DC/OS
* Updated methods where the above information is needed
* Fixed bug in test where the wrong instance was being passed
=> #938 - Error when generating job_type pointer to a secret setting

scale/job/models.py, scale/port/exporter.py
🐛 🐞 👣  Scale was passing the job_type interface directly to the configuration validation before running it through the JobInterface class to ensure it is the most recent version.
=> Bug fix - don't pass raw dict to configuration.validate()

scale/queue/job_exe.py, scale/scheduler/scheduling/manager.py, scale/scheduler/test/scheduling/test_manager.py
This PR is a scheduling fix that ignores queued jobs if the job references a job type or workspace that has not been synced to the scheduler yet. This can happen when a script loads things into Scale so quickly that the scheduler gets a job and doesn't know about its job type or workspaces yet.
=> Issue 953 - Scheduling fix

scale/job/apps.py, scale/job/execution/manager.py, scale/job/messages/job_exe_end.py, scale/job/test/execution/test_manager.py, scale/job/test/messages/test_job_exe_end.py, scale/messaging/apps.py, scale/scheduler/scale_scheduler.py, scale/scheduler/scheduling/manager.py, scale/scheduler/test/scheduling/test_manager.py, scale/scheduler/test/test_scheduler.py, scale/scheduler/threads/messaging.py
This issue represents the first use of the new backend messaging system.
1. Created the first message type that bulk creates job_exe_end models.
2. Created a new scheduler background thread that regularly submits messages to the message broker.
3. Updated the scheduler to submit canceled job_exe_end instances from queued jobs to the new background thread (through the JobExecutionManager).
=> Issue 962 - Use messaging system for canceled jobs on queue

scale/batch/models.py
Added check to ensure that only new/original jobs create a new batch_job.
Testing will be done in dev to ensure the desired outcome is achieved.
=> #963 -  Bug in batch creation of recipes with non-original jobs

scale/source/triggers/configuration/parse_trigger_rule.py
The new data_type filters were not being passed when determining if a condition was met.
=> #991 - New parse triggers not working

scale/docs/architecture/messaging.rst, scale/util/broker.py, scale/util/test/test_broker.py
* Updated docs to clean up formatting.
* Updated docs to remove requirement for trailing solidus. Solidus only needed when specifying broker virtual host
* Added support with regex to extract virtual host and eliminate trailing solidus requirement.
=> #997: Update docs and broker logic for AMQP / SQS messaging

scale/job/execution/tasks/cleanup_task.py
Added a bit of bash to detect any scale containers that are in a stuck state and delete them.  This will then allow the dangling volumes to be deleted. 
UPDATE: Tested on `dev`, everything appears to work well.
=> #952 - Docker cleanup fails on created containers

dockerfiles/framework/scale/bootstrap.py, dockerfiles/logstash/logstash.conf-template, scale/job/configuration/configurators.py, scale/job/test/configuration/test_configurators.py
added job_type to logstash output. 
added job_type to main_task_tag, separated by '++' and split out within logstash.conf-template
fixes #948
=> #948 Add job type to elasticsearch logs

scale/docs/rest/job.rst, scale/docs/rest/job_execution.rst, scale/job/models.py, scale/job/serializers.py, scale/job/test/test_views.py, scale/job/urls.py, scale/job/views.py
* Deprecated old views, functions, tests, serializers, and docs. 
* Added 2 new `/jobs/` endpoints for viewing job_exes associated with the requested job_id.
* Added views, functions, and serializers to handle the two new endpoints.
=> #983 - Create new job execution REST APIs

scale/scheduler/management/commands/scale_scheduler.py, scale/scheduler/threads/base_thread.py
I put in a fix so that when a thread detects a closed, unrecoverable database connection, the Scale scheduler shut downs (allowing it to be restarted by Marathon).
=> Issue 1031 - Scale does not recover from database crashes

scale/scheduler/database/updater.py, scale/scheduler/test/database/test_updater.py
Added additional logic to the database update system task to clean up any duplicate job executions (same job ID and execution number).
=> Issue 1077 - Clean up duplicate job executions

scale/job/apps.py, scale/job/messages/completed_jobs.py, scale/job/messages/failed_jobs.py, scale/job/messages/publish_job.py, scale/job/models.py, scale/job/test/messages/test_completed_jobs.py, scale/job/test/messages/test_publish_job.py, scale/recipe/messages/update_recipes.py
Created a new publish job message that gets sent when a job is both completed and has its output populated from its last execution.
=> Issue 1023 - Move product publishing to its own message

scale/job/views.py, scale/product/views.py, scale/queue/views.py, scale/recipe/views.py
I added a `get_serializer_class` method to every `v6` versioned API endpoint to simplify/centralize the serializer declaration.  
Because of this change I was able to refactor a lot of the versioned request view methods to simplify logic.  This involved removing `_v5` methods where allowed.  If the difference in logic was complex I left the separated methods. 
SB prediction: 23-21 Iggles 🏈 
Edit: Also this `get_serializer_class` method of assigning the serializer was tested on `dev` where `v4`, `v5`, and `v6` REST requests returned properly.
=> #1104 - Fix serializer declaration on views that use a deprecated serializer

scale/ingest/strike/monitors/dir_monitor.py
Code fix so that a file in the directory monitor does not have its file size checked without ensuring the file path is valid first.
=> Issue 1112 - Fix handling of missing transferring files

scale/job/messages/failed_jobs.py, scale/job/messages/process_job_inputs.py, scale/job/models.py, scale/job/test/messages/test_failed_jobs.py, scale/job/test/messages/test_process_job_inputs.py, scale/job/test/test_models.py, scale/queue/messages/queued_jobs.py, scale/queue/messages/requeue_jobs.py, scale/queue/messages/requeue_jobs_bulk.py, scale/queue/models.py, scale/queue/test/messages/test_queued_jobs.py, scale/queue/test/messages/test_requeue_jobs.py, scale/queue/test/test_models.py, scale/recipe/handlers/handler.py
Fixed the bug by using a flag in the queued_jobs message to distinguish between queuing for the first time and re-queuing. When re-queuing, CANCELED jobs can be QUEUED. When queuing for the first time, CANCELED jobs cannot be QUEUED.
=> Issue 1128 - Canceled Job Bug

scale/batch/models.py, scale/batch/test/test_views.py, scale/scheduler/database/updater.py, scale/scheduler/test/database/test_updater.py
Fixing a batch bug where the batch validation REST API errors if given an invalid previous batch and updated the database update to ensure old batches have their root batch ID correctly set.
=> Fix batch bugs

scale/docs/rest/source_file.rst, scale/source/test/test_views.py, scale/source/views.py
Updating v5 docs to deprecate Source File endpoints and disabling it in v6 endpoints.
=> Deprecating v5 Source File REST API

scale/batch/test/test_views.py, scale/batch/views.py
This is a bug fix for displaying recipe counts for a new batch when using the v5 batch details API.
=> Fix for displaying recipe counts for new batches in v5 API

scale/data/data/json/data_v6.py, scale/job/configuration/configuration.py, scale/job/configuration/exceptions.py, scale/job/configuration/json/job/job_config_v6.py, scale/job/configuration/mount.py, scale/job/configuration/volume.py, scale/job/test/configuration/json/job/test_job_config_v6.py
Created a new v6 job configuration. It is not yet connected to the configurator logic and it doesn't have v6 REST API docs yet. Both of these things will be implemented in the Seed integration branch.
The v6 job configuration has priority and output workspaces added to it in addition to the previous mounts and settings.
=> Issue 1105 - Create v6 job configuration

scale/batch/models.py, scale/batch/test/messages/test_update_batch_metrics.py, scale/docs/rest/v6/batch.rst
I updated the batch metrics generation to handle sub-recipes.
Recipe metrics generation already correctly sends batch metrics update messages only for top level recipes, so I didn't have to implement that.
=> Issue 1166 - Update batch metrics

scale/error/models.py, scale/error/test/test_models.py, scale/job/error/error.py, scale/job/test/error/test_error.py, scale/job/test/error/test_mapping.py
(1) and (2) seem to be fluke issues when we deployed to the dev DB. On both the prod DB and a clean DB, the 0005 error migration appears to generate the correct SQL commands.
Fixed the bug where updating an existing Seed error failed due to a null created time. Now the previous created time is queried and set on the model when updating.
=> Issue 1234 - Fix Seed error bugs

scale/job/seed/manifest.py, scale/job/test/seed/test_manifest.py
The Seed manifest has a few bugs where input file `mediaTypes` and output file `multiple` fields get overridden with their defaults. I fixed them.
=> Issue 1301 - Fix Seed manifest bugs

scale/job/models.py, scale/job/seed/manifest.py, scale/job/test/test_views.py, scale/job/test/utils.py
I fixed the bug so that minimum Seed manifests are correctly accepted by the v6 REST API.
If approved, please immediately merge and delete branch.
=> Issue 1307 - Fixed submitting Seed manifest without tags

scale/job/execution/configuration/configurators.py, scale/job/seed/types.py, scale/job/test/execution/configuration/test_configurators.py, scale/job/test/seed/test_types.py
- Pass `SYSTEM_LOGGING_LEVEL` to pre and post tasks
- Filter out special metadata files (`results_manifest.json`, `seed.outputs.json` and files ending in `.metadata.json`) from files returned by glob pattern matches
- Made file pattern matches log on info level
=> Output capture filters out special metadata files

scale/job/messages/purge_jobs.py, scale/job/messages/spawn_delete_files_job.py, scale/job/test/messages/test_spawn_delete_files_job.py, scale/recipe/apps.py, scale/recipe/instance/node.py, scale/recipe/instance/recipe.py, scale/recipe/messages/purge_recipe.py, scale/recipe/test/instance/test_recipe.py, scale/recipe/test/messages/test_purge_recipe.py, scale/recipe/test/utils.py, scale/storage/fixtures/delete_files_job_type.json, scale/storage/management/commands/scale_delete_files.py, scale/storage/messages/delete_files.py, scale/storage/test/management/commands/test_scale_delete_files.py, scale/storage/test/messages/test_delete_files.py
- Added `get_original_leaf_nodes` to `RecipeInstance`
- Added `trigger_id` passing to the rest of the purge stack
- Modified 'purge_jobs' to so that if the job had an is_original == True `RecipeNode` model attached to it it will pass a message for `purge_recipe`
- Added logic for purging recipes and their contents.  Expected behavior is: 
- message should retrieve the recipe instance and determine the current, original leaf nodes (is_original == True), send delete_job_files messages (with purge) for original leaf jobs and send purge_recipe messages for original leaf recipes
- if there are no original nodes left in the recipe, delete `BatchRecipe`, `RecipeNode` (matched on sub_recipe or recipe), `RecipeInputFile`, and `Recipe` model for this recipe ID
- if this recipe had a higher-level …
=> #1210 - Recipe purge

scale/job/messages/purge_jobs.py, scale/job/messages/spawn_delete_files_job.py, scale/job/test/messages/test_purge_jobs.py, scale/recipe/messages/purge_recipe.py, scale/recipe/test/messages/test_purge_recipe.py, scale/source/apps.py, scale/source/messages/purge_source_file.py, scale/source/test/messages/test_purge_source_file.py, scale/storage/messages/delete_files.py
- Added `purge_source_file` message type with expected `execute()` behavior of: 
```
1. If there are any non-superseded recipes with this file as input, 
send purge_recipe messages for them
2. If there are any non-recipe jobs with this file as input, 
send delete_job_files messages for them
3. If there are zero from (1) and (2), 
delete the `Ingest` and `ScaleFile` models for the source file. 
```
- Added `purge` flag passing to `purge_recipe`, `purge_jobs` and `delete_files`
- Modified `purge_job` to send a `purge_source_file` message for any input files if the job is not part of a recipe.
- Modified `purge_recipe` to send a `purge_source_file` message for any input files if it is its own root superseded recipe
**I will update the command messages wiki page after review but before …
=> #1211 - Purge source file message

scale/job/messages/purge_jobs.py, scale/job/messages/spawn_delete_files_job.py, scale/job/test/messages/test_purge_jobs.py, scale/job/test/messages/test_spawn_delete_files_job.py, scale/recipe/messages/purge_recipe.py, scale/recipe/test/messages/test_purge_recipe.py, scale/source/messages/purge_source_file.py, scale/storage/fixtures/delete_files_job_type.json, scale/storage/management/commands/scale_delete_files.py, scale/storage/messages/delete_files.py, scale/storage/test/management/commands/test_scale_delete_files.py, scale/storage/test/messages/test_delete_files.py
- Added `source_file_id` passing to the messages that are involved with the purge process. 
- Modified `purge_job` and `purge_recipe` to use the given `source_file_id` when calling `purge_source_file` instead of doing a database operation. 
**I will update the command metrics wiki page after review but before merge**
=> #1342 - Fix purge workflow to only purge the given source file

scale/recipe/messages/create_recipes.py, scale/recipe/messages/reprocess_recipes.py, scale/recipe/test/messages/test_create_recipes.py
Deprecated the old `reprocess_recipes` message in favor of using the `create_recipes` message to do reprocessing.
=> Issue 1172 - Update message to reprocess recipes

scale/queue/models.py, scale/recipe/apps.py, scale/recipe/definition/json/definition_v6.py, scale/recipe/messages/process_condition.py, scale/recipe/models.py, scale/recipe/test/messages/test_process_condition.py, scale/recipe/test/utils.py
Created a new message, `process_condition`, that grabs a condition's data from its recipe dependencies, applies its data filter to the data, and saves whether the data is accepted or not. Then it sends a message to update the condition's recipe so the recipe can execute the nodes depending on the condition (or not).
=> Issue 1174 - Message for recipe conditions

scale/data/data/json/data_v6.py, scale/data/data/value.py, scale/job/data/job_data.py, scale/job/test/execution/configuration/test_configurators.py, scale/job/test/seed/test_job_data.py, scale/queue/test/test_models.py
Added a multiple field on the FileValue class in order to properly set the injected input file value. Instead of checking the number of file ids being passed to the job, the new multiple value is checked.
=> #1409 Setting injected input variable correctly if multiple inputs

scale/job/migrations/0050_auto_20181109_2037.py
The job data migration was performing a `len(job_input['files']['input_file']>1)` when it should have been doing `len(job_input['files']['input_file']) > 1`
=> Correcting TypeError: object of type 'bool' has no len()

scale/job/messages/purge_jobs.py, scale/recipe/messages/purge_recipe.py, scale/storage/messages/delete_files.py, scale/storage/test/messages/test_delete_files.py
Found bug in testing purge where the `file_ancestry_link` needs to be deleted before the product `scale_file` record can be purged. 
I don't think the increment logic worked before, this should.
=> Purge fixes

scale/ingest/strike/monitors/s3_monitor.py, scale/ingest/test/strike/monitors/test_s3_monitor.py
In testing this against actual S3 and SQS messages, it appears the SQS message format is different from how this was originally coded.  Making this change made the monitor work with standard SQS S3 notification event messages.
=> Fixed code that was incorrectly processing SQS messages

scale/job/execution/configuration/configurators.py, scale/job/test/execution/configuration/test_configurators.py
job/execution/configuration
Added a new environment variable INPUT_METADATA to each Scale task that includes inputs for the specific job,. as well as the inputs for the encompassing recipe. The environment variable is a stringified json object in the form of:
```
INPUT_METADATA = {
'JOB': {'input_1_name': ['public/facing/url/to/input', 'public/facing/url/to/input/2'], 'input_2_name': ['public/facing/url/to/input']},
'RECIPE': {'input_1_name': ['public/facing/url/to/input'], 'input_2_name': 'my_json_value'}
}
=> #1458 - Inject Recipe Metadata As Environment Variables To Each Job

scale/recipe/instance/recipe.py, scale/recipe/test/messages/test_purge_recipe.py
- recipe
- Added a simple `is_real_node` check when gathering recipe nodes that need to be purged. 
- Full disclosure: I was not able to reproduce this error with just a Scale test.  I have no idea how a DummyNode came into existence with a `node_type` that equals `JobNodeDefinition.NODE_TYPE`
https://github.com/ngageoint/scale/blob/8d8cca814936528a333374e35af5122e652f4900/scale/recipe/messages/purge_recipe.py#L94
is getting back `DummyNodeInstance` when it is expecting only `JobNodeInstance`.
Error (actual error is on Line # 96):
```AttributeError: 'DummyNodeInstance' object has no attribute 'job' ```
Also may apply to:
https://github.com/ngageoint/scale/blob/8d8cca814936528a333374e35af5122e652f4900/scale/recipe/messages/purge_recipe.py#L102
=> Issue 1429 - purge_recipe unexpected function return

scale/recipe/serializers.py, scale/recipe/test/test_views.py
- Recipe
Fixed broken recipe type details serializer
=> #1472 - Fix recipe type details serializer

scale/queue/models.py, scale/queue/test/test_models.py
- queue
If a job is re-queued when it is already in the queue there will be two copies of the job in the queue.  If one of the copies will never be scheduled (e.g. due to invalid resource requirements) it will sit on the queue forever and there's no easy way to get rid of it.  In this scenario it can be assumed that if a user wants to re-queue a job already in the queue, the job already in the queue can be deleted and replaced with the new one.
=> #1494 - Requeueing queued jobs

scale/docs/rest/v6/job_type.rst, scale/docs/rest/v6/job_type.yml, scale/job/models.py, scale/job/test/test_views.py, scale/job/urls.py, scale/job/views.py
-jobs
Changing job-types endpoint to return list of all job types and added job-type-names endpoint to return the list of job type names previously returned by the job-types endpoint.
=> #1503 - Job Type Names fields 

scale/docs/rest/v6/metrics.yml, scale/docs/rest/v6/recipe_type.rst, scale/job/models.py, scale/job/test/test_views.py, scale/scheduler/manager.py, scale/scheduler/scheduling/manager.py
-job
-scheduler
Fixing scheduling logic to skip job types that have been marked as having invalid resource requirements for awhile, and only attempt to schedule them again either after a timeout period or after the job type has been updated and the flag reset.  If a job type is again able to be rescheduled due to the needed resource being offered, unset the flag.  Also, added warning when validating a job type with a nonstandard resource (#1493) and cleaned up some documentation TODOs.
=> #1511 - Reset unmet_resources flag

scale/job/messages/completed_jobs.py, scale/job/messages/failed_jobs.py, scale/job/messages/job_exe_end.py
- job
Added retry decoration for three messages that are having deadlock issues.  I believe this should allow scale to retry these messages 5 times and one of these retries should succeed as the failures are only happening sporadically.  This should have the same result the current code achieves by retrying the message when this occurs but without filling up the error log.
=> #1102 - Fix deadlocks when locking job models

scale/data/data/data.py, scale/data/test/data/test_data.py, scale/ingest/urls.py, scale/job/configuration/data/job_data.py, scale/job/configuration/results/results_manifest/results_manifest.py, scale/job/data/job_data.py, scale/job/messages/process_job_input.py, scale/job/seed/results/job_results.py, scale/job/serializers.py, scale/job/test/configuration/interface/test_job_interface.py, scale/job/test/messages/test_process_job_input.py, scale/product/urls.py, scale/recipe/serializers.py, scale/recipe/test/test_views.py, scale/recipe/urls.py
- data
- ingest
- job
- product
- recipe
Fix for serializer bug (#1538), a bug with periods in urls (#1536) and a bug causing jobs to be stuck pending in recipes.  A legacy job type can execute successfully without creating required output.  This leaves jobs connected to such outputs stuck in a pending state, unable to be queued.  This fix cancels any such pending jobs and any future jobs that get in this state.  Also, jobs that finish without creating required output are marked as failed instead of completing successfully.
=> #1537 - Legacy Job Data is not populated

scale/job/configuration/data/job_data.py, scale/source/apps.py
- [x ] `manage.py test` passes
job
The job_data.save_parse_results expects a data file parse saver class to be registered. This was incorrectly un-registered/removed from scale/source/apps.py when triggers were fully removed. There was also a leftover is_recipe parameter from the trigger transition that was not removed.
=> #1542 Fixing save_parse_results bug

dockerfiles/framework/scale/bootstrap.py
None
Deployments were failing when testing with a tagged release of Scale and no `LOGSTASH_DOCKER_IMAGE` being set. This PR hardens the logic to ensure we are actually suffixing the image name properly when multiple colons exist in the Docker image (port and tag exist). This was only seen when pulling a Scale release from a Docker registry that had a port specified.
=> #1541 - Logstash Docker tag match to Scale on release

scale/job/seed/manifest.py
job
fixed a bug in validate_resources where verifying a float is a whole number would crash if an int was passed in instead.
=> added check to verify value is a float before calling is_intiger

scale/cli/management/commands/migratedata.py, scale/ingest/triggers/ingest_recipe_handler.py, scale/job/configuration/data/job_data.py, scale/job/execution/configuration/configurators.py, scale/job/messages/process_job_input.py, scale/job/models.py, scale/job/test/execution/configuration/test_configurators.py, scale/job/test/utils.py, scale/queue/models.py, scale/queue/test/test_models.py, scale/recipe/instance/node.py, scale/recipe/models.py, scale/recipe/test/messages/test_create_recipes.py, scale/recipe/test/test_views.py, scale/recipe/test/utils.py, scale/recipe/views.py
- job
- recipe
Fixing an infinite message loop that occurs when canceling a job due to failing to process input and fixing reprocessing endpoints so legacy recipe workspace information isn't lost.
=> #1555 - Reprocess Recipe Fails

scale/job/configuration/configuration.py, scale/job/configuration/data/job_data.py, scale/job/test/configuration/data/test_job_data.py, scale/recipe/test/messages/test_create_recipes.py, scale/recipe/test/test_views.py
- job
- recipe
Fixed invalid property name and changed output workspace code to always attempt to use job configuration workspaces if present.
=> #1559 - Job Configuration Bugs

scale-ui/app/modules/charts/donut/donutController.js
Bugfix that removes a duplicate property which was preventing the UI from loading in IE 11. Fixes #1568
=> #1568 - Scale UI unavailable in IE 11

scale-ui/app/modules/overview/controllers/ovController.js
Changed the jobs grid on the dashboard to pull from the `job-types/running/` endpoint. Closes #1570
=> #1570 - Only Show Current Job Types in Dashboard

scale/messaging/manager.py, scale/product/models.py, scale/recipe/apps.py, scale/storage/apps.py
- messaging
- product
- recipe
- storage
Fixes for #1571 and #1574
=> #1574 - Update Recipe Definition Message Not Added to Message Factory 

scale/batch/test/test_views.py, scale/batch/views.py, scale/recipe/messages/create_recipes.py, scale/recipe/test/messages/test_create_recipes.py
- recipe
Fixing message bomb caused when calling create recipe messages with over 100 recipes.  The message variable was never reset, so if you had 101 recipes you ended up with two messages with the same 101 recipes in both.
=> #1580 - Batches Taking Too Long

scale/docs/rest/v6/recipe.rst, scale/docs/rest/v6/recipe.yml, scale/recipe/test/test_views.py, scale/recipe/views.py, travis-build.sh
recipe
The recipe reprocessing endpoint was updated to always pull the latest revision of the recipe type, unless 'revision_num' is specified in the incoming json data. If the revision number is not found a 404 is returned (same as if recipe id not found).
=> #1601 Reprocessing Recipe Doesn't Use Latest Revision

scale/job/migrations/0054_convert_manifest.py, scale/metrics/daily_metrics.py, scale/metrics/fixtures/metrics_job_types.json, scale/metrics/test/test_daily_metrics.py, scale/recipe/test/test_views.py, scale/recipe/views.py, scale/util/rest.py
job/migrations
recipe-types/ POST api call
Scale Daily Metrics system job
Scale Strike system job
#1636 
Added checking to return an error when a duplicate recipe type is detected on POST. An error message will be returned instead of allowing the duplicate recipe type to be created.
#1638 
The migration to convert legacy job types to seed job types neglected to also update any recipe types that referred to those jobs. This was causing a server 500 error to occur at the v6/recipe-types end point.
#1640
The Scale Daily Metrics job was failing to substitute properly due to the command argument definition of `${:Day}` instead of `${DAY}`. Also updated the Scale Strike system job to reference the strike id argument consistently as STRIKE_ID.
=> #1636 Duplicate Recipe Types / #1638 Update legacy job type migration / #1640 Fix system jobs

scale/accounts/test/test_views.py, scale/job/configuration/configuration.py, scale/job/seed/results/job_results.py, scale/job/test/test_views.py
- accounts
- job
Switching from accessing 'files' and 'json' directly to instead use get method and return empty lists if they are missing.
=> #1604 - Seed manifest with no output files

scale/ingest/fixtures/ingest_job_types.json, scale/ingest/models.py, scale/job/execution/configuration/configurators.py, scale/job/migrations/0056_convert_strike_jobs.py, scale/job/test/execution/configuration/test_configurators.py, scale/job/views.py
Strike/Scan system jobs
ingest
job
#1648 
Added serializer_class to RequeueJobsView to fix server 500 error
#1650 
Included migration to update any existing Strike jobs to reference the updated json input ID STRIKE_ID. Also updating migration to update any existing Scan jobs.
=> #1648 serializer_class missing from RequeueJobsView / #1650 Strike/Scan job updates

scale/pip/production.txt, scale/pip/requirements.txt, scale/scale/settings.py
- all/none
Changed the requirements for DRF to >= 3.9.1 to address xss vulnerability.  We need to check if there is anything in 3.7, 3.8 or 3.9 that breaks our workflow but the tests pass after fixing the new path for the filter backend.
=> #1661 - Fix Security Vulnerability

dockerfiles/framework/scale/app-templates/silo.json, dockerfiles/framework/scale/app-templates/ui.json, dockerfiles/framework/scale/bootstrap.py, scale/README.md
Resolution of the Silo deployment not including a default collection of images. I updated the deploy to include a newer build of Silo as a default, so that the Silo schema could co-exist in the Scale postgres database. 
The following deployment environment variables have been changed:
* `ELASTICSEARCH_DOCKER_IMAGE`: Updated to properly match the value in bootstrap of `elasticsearch:5-alpine`
* `SILO_DOCKER_IMAGE`: Updated to new Silo release supporting proper PG data storage. `geoint/seed-silo:0.8.0` 
* `SILO_HUB_ORG`: If `SILO_URL` is unset, will be used to initialize Silo against a _public_ only Docker Hub organization.
* `SILO_URL`: Renamed from `SILO_ADDRESS`. If left empty, Silo will be deployed. Should be set in production.
=> #1631 - Fixes for Silo deploy

dockerfiles/framework/scale/app-templates/ui.json, dockerfiles/framework/scale/app-templates/webserver.json, scale/scale/local_settings_docker.py
Fixes #1654, but an additional commit is required in ngageoint/scale-ui.
HAProxy settings are changed to conditionally send `X-Forwarded-Proto = https` if the client protocol is in fact `https`. At least with the version of DC/OS used off-site, it appears that using `HAPROXY_0_BACKEND_HTTP_OPTIONS` in combination with `HAPROXY_0_BACKEND_REDIRECT_HTTP_TO_HTTPS` may make the former option take precedence. `HAPROXY_0_REDIRECT_TO_HTTPS` seems to allow for the desired effect.
Django also has to be configured to allow this header to be recognized, via `SECURE_PROXY_SSL_HEADER`, which will let it build URIs correctly. This is still needed even if the https redirect is not wanted, since it will conditionally build the URIs according to the scheme passed down through the proxies.
The same HAProxy …
=> Partial fix for sending correct headers from HAProxy through to Django

dockerfiles/framework/scale/bootstrap.py
Updates the deployment to always attempt updates in place, instead of the present approach of force delete followed by redeploy. This eliminates the issue with fluentd being deleted and then note able to deploy due to extended removal time / locked deployment.
This change impacts all services, but is most visible with `scale-fluentd`, `scale-ui` and `scale-webserver` services.
=> #1589 - Resolve fluentd deployment issue

scale/batch/test/test_views.py, scale/job/test/test_views.py
- batch
- job
Some tests I wrote when trying to reproduce #1645. This will ensure we don't break this in the future.
=> #1645 - v6 batches don't override priority

.travis.yml, scale/ingest/apps.py, scale/ingest/ingest_job.py, scale/ingest/messages/create_ingest_jobs.py, scale/ingest/models.py, scale/ingest/strike/monitors/monitor.py, scale/ingest/test/messages/__init__.py, scale/ingest/test/messages/test_create_ingest_jobs.py, scale/ingest/test/test_models.py, scale/ingest/test/test_views.py, scale/ingest/test/triggers/test_ingest_recipe_handler.py, scale/ingest/triggers/ingest_recipe_handler.py, scale/job/messages/create_jobs.py, scale/job/messages/process_job_input.py, scale/job/test/execution/configuration/test_configurators.py, scale/job/test/test_views.py, scale/job/views.py, scale/metrics/daily_metrics.py, scale/metrics/test/test_daily_metrics.py, scale/queue/models.py, scale/recipe/messages/create_recipes.py, scale/recipe/models.py, scale/recipe/test/messages/test_create_recipes.py, scale/recipe/views.py, scale/scheduler/initialize.py, scale/scheduler/test/test_initialize.py, scale/util/database.py, travis-build.sh
ingest
recipe
queue
#1656 
Recipes were not being kicked off from ingested files consistently (I'd see maybe one being queued, the rest of the time there would be recipe/job id not found exceptions cluttering up the logs). Added two command messages to handle creating ingest jobs and creating new recipes:
create_ingest that will handle creating the ingest job
create_new_recipe that handles actually creating the new recipe and processing recipe input. We already had a message for creating sub recipes and reprocessing recipes, but creating new ones hadn't been done yet.
=> #1656 - Consistent processing

scale/recipe/models.py, scale/recipe/test/test_views.py
Recipe
Updated the create recipe process so that if a warning is detected about not being able to reprocess the recipe it will still be considered valid.
=> #1688 - Recipe Type Validation Returning Invalid for Warning

scale/batch/test/test_views.py, scale/batch/views.py, scale/ingest/test/test_views.py, scale/ingest/views.py, scale/storage/test/test_views.py, scale/storage/views.py
- batch
- ingest
- storage
Changing validation endpoints to return 200 OK response with errors listed in response.
=> #1701 - Validation responses with errors return as a 400

scale/job/models.py, scale/job/seed/manifest.py, scale/job/test/test_views.py, scale/scheduler/scheduling/manager.py
- job
- scheduler
Fixed some code that was inside of loops that shouldn't be.
Since resource names are converted to lowercase everywhere they are used, the names are now changed when retrieved from the manifest for consistency.
The lists of job types and their resources in the manager is now synced with the database when a job type is edited so we don't get stuck in a loop where unmet_resources is cleared and then reset to the old value by the scheduler.
'sharedmem' is ignored by the code checking for unmet resources.
=> #1720 - sharedMem not supported

scale/docs/rest/v6/job_type.rst, scale/docs/rest/v6/job_type.yml, scale/job/models.py, scale/job/test/test_views.py, scale/job/views.py
job
#1721 
Updated the job-type POST and job-type/name/version PATCH endpoints to update the same fields when editing an existing job type. Added the `is_paused` and `is_active` fields to the job-type/ POST, and `docker_image` and `manifest` fields to the PATCH. An error is returned during the PATCH if the name or version from the manifest does not match the name and version of the job type being updated.
=> #1721 Job Type POST/PATCH Endpoint Consistency

.travis.yml, scale/docs/rest/v6/deprecated.rst, scale/docs/rest/v6/ingest.rst, scale/docs/rest/v6/job.rst, scale/docs/rest/v6/job_type.rst, scale/docs/rest/v6/job_type.yml, scale/docs/rest/v6/node.rst, scale/docs/rest/v6/recipe.rst, scale/docs/rest/v6/recipe_type.rst, scale/docs/rest/v6/recipe_type.yml, scale/docs/rest/v6/scale_file.rst, scale/docs/rest/v6/strike.rst, scale/docs/rest/v6/workspace.rst, scale/job/job_type_serializers.py, scale/job/models.py, scale/job/test/test_views.py, scale/job/views.py, scale/recipe/models.py, scale/recipe/serializers.py, scale/recipe/test/test_views.py, scale/recipe/views.py, travis-build.sh
- job
- recipe
Added fields to job-type details and recipe-type details apis to show which recipes each belongs to so they can be easily found if they need to be edited.
Automatically deprecate parent recipes when jobs/recipes are deprecated regardless of auto-update flag. Parent recipes aren't automatically reactivated.
Changed job/recipe patch endpoints to return 200 OK response with validation dict for warnings.
=> #1718 - Deprecation Warning

scale/job/views.py, scale/recipe/views.py
- jobs
- recipes
`/v6/jobs/` and `/v6/recipes/` were both performing extra queries, `n+1` for each item returned, as outlined in #1717.
For jobs, despite being in `select_related()`, the nested `job_type_rev__job_type` was being queried for each result. The docs say that fields in the `defer()` list can also be `select_related()`, but maybe this doesn't play well with DRF serializers? Similar situation for recipes endpoint.
I didn't put this change in the manager (where the `select_related()`/`defer()` currently happens) in case this messes up performance elsewhere.
For the jobs endpoint, this cuts queries from 36 (449 ms) to 4 (152 ms). Recipes endpoint is similar, but not as extreme.
=> Issue 1717 - Optimize API responsiveness for jobs and recipes

scale/job/configuration/interface/job_interface.py, scale/job/data/job_data.py, scale/job/execution/configuration/configurators.py, scale/job/execution/container.py, scale/job/management/commands/scale_pre_steps.py, scale/job/seed/manifest.py, scale/job/test/execution/configuration/test_configurators.py, scale/job/test/management/commands/test_scale_pre_steps.py
- job
Fixing input metadata manifest so clint can actually write new publishers.
=> #1775 - Input metadata manifest json

scale/job/execution/container.py, scale/job/management/commands/scale_pre_steps.py, scale/job/test/management/commands/test_scale_pre_steps.py
- The `SCALE_INPUT_METADATA_PATH` file doesn't exist so it needs the `+` operator on open.
- The `tmp` folder does not exist so it needs to be made.
=> Input metadata small fix

scale/job/execution/configuration/configurators.py, scale/job/test/execution/configuration/test_configurators.py
- job
The configuration code uses the latest manifest for a job type when configuring a job but it should use the manifest for the revision the job was created with.
=> #1782 - Jobs Always Configured with Newest Manifest

scale/job/test/test_views.py, scale/job/views.py, scale/recipe/test/test_views.py, scale/recipe/views.py
- job
Fixed 500 errors for invalid job type fields, added auto_update as a valid field for job type patch endpoint and made auto_update default to true. The last one doesn't help when using the UI so the UI needs to be updated to default to true as well.
=> #1785 : Allow auto_update on job type patch

scale/metrics/serializers.py, scale/metrics/test/test_views.py
metrics
The PlotDataValueSerializer was not returning the `id` field utilized by the UI in certain plots. Updated the serializer to always include this field - stripping it out if not populated.
=> Simplifying metrics - will return ids in plot data values when populated

scale/docs/rest/v6/system.rst, scale/docs/rest/v6/system.yml, scale/scheduler/test/test_views.py, scale/scheduler/views.py, scale/util/rest.py
- scheduler
Return a 503 with a custom message indicating stale/missing scheduler status instead of vague 204
=> #1770 - Provide better return indicating stale scheduler

scale/scheduler/resources/manager.py, scale/scheduler/test/resources/test_manager.py
- scheduler
Catch exceptions encountered when getting agent resources from mesos (caused by masters restarting or anything else) and shutdown scale if exceptions continue to occur for 30 minutes. We may want to pause the scheduler and/or raise an error instead of shutting down.
=> #1778 - Empty Mesos Resources Response

scale/docs/rest/v6/ingest.yml, scale/docs/rest/v6/strike.rst, scale/ingest/strike/monitors/dir_monitor.py, scale/ingest/test/strike/monitors/test_dir_monitor.py
ingest
made transfer_suffix optional for directory strikes.
=> #1768 - Transfer_suffix required for directory strikes

scale/pip/docs.txt
mkdocs requires python 2.7.9+ as of version 1.0.0. We currently use 2.7.5 so attempting to install the latest mkdocs available fails and the documentation is not built.
pip/docs.txt
mkdocs requires python 2.7.9+ as of version 1.0.0. We currently use 2.7.5 so attempting to install the latest mkdocs available will fail and the documentation will not be built during the docker build.
=> Set mkdocs version

scale/job/migrations/0054_convert_manifest.py
job/migration/0054_convert_manifest.py
During the manifest conversion, the error type was being set to `algorithm` when it should have been `job`. Also removed an unused import.
=> Couple fixes for the legacy -> seed manifest conversion migration

scale/recipe/models.py, scale/recipe/test/test_views.py
recipe
Updated the Edit/Validate logic to check for sub-recipes of the same time of the recipe being edited. This validation will drill down into each sub-recipe to ensure we don't have a loop anywhere.
Addresses #1808
=> Validate Recipes Don't Contain Sub-recipes of Themselves

dockerfiles/examples/source-metadata/Dockerfile, dockerfiles/examples/source-metadata/generate-metadata.sh, dockerfiles/examples/source-metadata/seed.manifest.json, scale/job/data/job_data.py, scale/job/seed/manifest.py, scale/job/seed/metadata.py, scale/job/seed/results/job_results.py, scale/job/seed/results/outputs_json.py, scale/job/seed/types.py, scale/job/test/seed/results/test_job_results.py, scale/job/test/seed/test_job_data.py, scale/source/configuration/source_data_file.py, scale/source/models.py, scale/source/test/configuration/test_source_data_file.py, tests/postman/full-host-test.json
* job
* storage
Add the ability to capture supplemental metadata to attach to `SOURCE` files. The only reason for this is to support augmentation of metadata associated with files that domain specific jobs can provide - the Scale Ingest doesn't have the smarts for it, nor should it.
We are expanding on the use of the metadata sidecar file for input files. There are some small differences. Since we can't guarantee writable storage within the input location, we must write them to the output directory. Details on the format and location of the metadata json can be found in the documentation here: https://github.com/ngageoint/scale/wiki/Scale-Job-Inputs-and-Outputs#source-input-metadata
The reason we are using the input file name as opposed to the same name as the input file name is because …
=> #1289: Parse results / Source Metadata Augmentation

scale/ingest/test/test_views.py, scale/ingest/views.py, travis-build.sh
ingest
whenever the workspace of a strike is changed, the strike job will now stop and restart to apply the new workspace.
=> 1736 - Strike doesn't properly reload configurations

scale/pip/production.txt, scale/pip/requirements.txt
The `marathon` library was causing builds to fail because it had python 3 code that was trying to execute.
=> Dependency: Restrict marathon library version

scale/docs/rest/v6/scan.rst, scale/ingest/models.py, scale/ingest/test/test_views.py, scale/ingest/urls.py, scale/ingest/views.py
ingest/scan
added scan cancel API endpoint, during development ended up fixing an ingest/scan bug as well.
=> #1741, #1822 - Can't Cancel Scan, get ingest details with no associated strike causes server error

scale/recipe/definition/node.py
recipe
Support for checking optional output existence was added a while back, however we weren't checking the existence of the object before trying to access it.
=> Checking optional outputs for existence before accessing

scale/docs/rest/v6/scheduler.rst, scale/docs/rest/v6/scheduler.yml, scale/scheduler/scheduling/manager.py, scale/scheduler/serializers.py, scale/scheduler/test/scheduling/test_manager.py, scale/scheduler/test/test_views.py, scale/scheduler/views.py
scheduler
#1801: Updated the scheduler logic to pack in jobs as long as we're under the queue limit (500) instead of just grabbing the first 500 from the queue regardless of schedulability.
#1802: Added logging statements to the scheduler loop.
#1815: Added queue_mode to the serializer/patch arguments to support dynamically changing the queue order from LIFO to FIFO and vice versa.
=> #1801, #1802 & #1815 - Scheduler

scale/ingest/models.py, scale/ingest/test/test_views.py, scale/ingest/views.py
ingest
Updated the logic that returned the ingest status to only include values from the given time range instead of the beginning of the start day and end of the end day.
=> #1835 Return Ingest Status By Given Started/End Dates

scale/batch/configuration/configuration.py, scale/batch/configuration/json/configuration_v6.py, scale/batch/definition/definition.py, scale/batch/messages/create_batch_recipes.py, scale/batch/models.py, scale/batch/test/configuration/test_configuration.py, scale/batch/test/definition/test_definition.py, scale/batch/test/messages/test_create_batch_recipes.py, scale/batch/test/test_views.py, scale/batch/views.py, scale/data/models.py, scale/data/serializers.py, scale/data/test/test_models.py, scale/data/test/test_views.py, scale/data/views.py, scale/docs/rest/v6/batch.rst, scale/docs/rest/v6/batch.yml, scale/docs/rest/v6/data.rst
batch
Added an optional `inputMap` to the batch configuration. This configuration value maps the recipe input name to a dataset parameter name, therefore allowing datasets with parameters named differently than recipe inputs to be used in a batch.
=> Add inputmap to batch configuration

scale/metrics/fixtures/metrics_job_types.json, scale/metrics/models.py, scale/metrics/test/test_models.py, scale/metrics/test/test_views.py
metrics
Updated the calculation method of the daily metrics (ingest, error, and job-type) to bin the metrics data by hour instead of simply daily totals. One thing to consider is this will expand the database records significantly since we are now storing records for each hour per job type instead of each day per job type.
=> #1839 Daily Metrics Binned by Hour

scale/job/test/utils.py, scale/node/models.py, scale/node/test/test_models.py, scale/scheduler/node/manager.py, scale/scheduler/test/node/test_manager.py
- node
- scheduler
The original `job_exe_end` and `job_exe` query was terrible for many reasons.  I changed it to just get the node to job relation which should be much faster.  Fixed tests and added `node` assignment to the the test utils.
=> Scheduler node fix

scale/pip/production.txt, scale/pip/requirements.txt
Pinning the zipp version to less than 2.0.0 due to support for Python 2.7 was discontinued in >= 2.0.0
pip/production.txt
pip/requirements.txt
Zipp >= 2.0.0 discontinued support for Python 2.7. Due to dependencies on this library, we need to pin the version of zipp we're pulling to < 2.0.0
=> Pinning zipp to < 2.0.0

scale/docs/rest/v6/job.rst, scale/job/job_type_serializers.py
job
Added `is_system` to the serializer for the base jobtype. This should add this field to the serializer utilized by the /jobs endpoint to satisfy #1843.
=> Adding is_system to jobtype base serializer

dockerfiles/framework/scale/bootstrap.py, scale/README.md, scale/scale/settings.py, scale/scheduler/scheduling/manager.py
settings
Added a SCHEDULER_QUEUE_LIMIT variable in order to dynamically update the number of queues we process at a time (rather than hard code 500). This is to temporarily address #1801 by allowing us to up the queue limit in order to bypass the unschedulable jobs blocking the queue.
=> Adding SCHEDULER_QUEUE_LIMIT as environment variable

scale/docs/rest/v6/job.rst, scale/docs/rest/v6/job.yml, scale/job/models.py, scale/job/serializers.py
job
#1859 
Updated the JobSerializerV6 to include an `input_files` JSON field that lists all input file names for each input in the format: 
```
{
"input_files": {"INPUT_FILE": ["file1-name.filext"], "INPUT_FILE_2": ["file2-name.filext", "file3-name.filext"]}
...
}
```
This change allows the input file list to be displayed in the Jobs table to satisfy the requirements of https://github.com/ngageoint/scale-ui/issues/414
=> #1859 Add input file info to /jobs API

scale/ingest/messages/create_ingest_jobs.py, scale/ingest/test/messages/test_create_ingest_jobs.py
ingest
The Scale Ingest processing message was creating unnecessary extra process_job_input messages after creating the ingest job resulting in 'input file for job xxx already processed' being logged in the message handler. I thought this had already been taken care of but apparently not?
=> Removing Unnecessary Scale Ingest Process Job Input Messages

scale/pip/production.txt, scale/pip/requirements.txt, scale/scale/settings.py, scale/scale/urls.py
- global change
This adds support for [django-debug-toolbar](https://django-debug-toolbar.readthedocs.io). This provides a collapsible sidebar ([panels](https://django-debug-toolbar.readthedocs.io/en/latest/panels.html))on the right side of any HTML encoded response. Primarily, this will expose the ability to see the exact SQL query and timing data directly on an API endpoint.
This is enabled in production, but will only be visible by setting `INTERNAL_IP` environment variable to your client's IP (ex, your laptop is set to 192.168.1.100). This has not been tested with the many layers of proxies in our various prod environments, but I think it should work. Alternatively, I usually have a separate `requirements.dev.txt` that only installs the package, then in `settings.py`:
```py
try: …
```
=> Basic setup for django-debug-toolbar

scale/accounts/templates/accounts/login.html
Fixes #1788 
- Django's auth
This creates a bit more of a standard login form for SSO-enabled auth. Template logic was based on django-crispy-forms.
Normal login:
Field-level validation:
Form-level validation:
With GEOAxIS enabled:
We can also move the single sign on section to the right (split the main box into two columns).
=> Issue 1788 - Better login form

scale/ingest/models.py, scale/ingest/test/triggers/test_ingest_recipe_handler.py, scale/ingest/triggers/ingest_recipe_handler.py, scale/queue/models.py, scale/recipe/messages/process_recipe_input.py, travis-build.sh
ingest
Once upon a time, a long time ago, a developer relatively new to the project noticed there seemed to be inconsistencies with getting jobs to schedule. 
Aha! They thought. Most of the communication seems to happen with messaging! I shall create a command message to create ingest jobs since that seems to be how the rest of the project works! 
And so it came to pass every Scale ingest required first a message to create the ingest task, then a message to complete the task and process the corresponding recipes. This appeared to work for a while, until it became clear these messages served no purpose and were contributing to a large message backlog the handlers struggled to get through. 
That same developer, now wiser (hopefully) in the ways of the codebase, has created this attempt to …
=> Remove Command Messages for Ingests

scale/scheduler/scheduling/manager.py
scheduler 
Removed the warnings on every pass of the process queue loop in favor of a "[count] [job_type_name] job types could not be scheduled due to [reason]" warning at the end of the processing loop. scale-ingests exceeding their scheduling limit were overrunning the output logs.
=> Cooling off on the logging

dockerfiles/framework/scale/scale.conf, scale/pip/docs.txt
framework/../scale.conf
scale/pip/docs.txt
Had to add a "Require all granted" clause for the scale/docs directory in order to resolve an AH01630 client denied by server configuration error that was being logged in the webserver.
Updated the mkdocs versions requirements as the latest versions of dependencies did not support Python 2.7 and were therefore failing to build the docs.
=> Resolving AH01630 Error

scale/storage/models.py
Fixes #1831
- storage
Much faster query response can be achieved by moving `'job_type'` from `.select_related()` to `.prefetch_related()`. See metrics in issue for more detail.
=> #1831 Optimize /files

scale/docs/rest/v6/recipe.rst, scale/docs/rest/v6/recipe.yml, scale/recipe/models.py, scale/recipe/serializers.py, scale/recipe/views.py
- recipe
Fixes #1893. Provides a query filter on `/recipes` list view to filter by `root_recipe_ids`. Also adds database optimizations for anything that has a parent recipe serialized, 800+ queries down to 5.
=> #1893 Filter for parent recipes

scale/environment/mac-init.sh
- [x ] `manage.py test` passes
- [x ] tests are included
- [x ] migrations are included
- [x ] documentation is changed or added
- Scale
Fixed issue by calling virtualenv from python2.
=> virtualenv command is not found by default on mac. 

web-docs/flow.html, web-docs/index.html, web-docs/quickstart.html, web-docs/walkthrough/index.adoc
#1890 - Eliminate use of ENTRYPOINT in Scale Walkthrough
Documentation
Update the example in the Scale walkthrough to eliminate the use of `ENTRYPOINT` in the Dockerfile to more closely match the Seed user guide example.
=> Update Scale Walkthrough to eliminate use of ENTRYPOINT

web-docs/walkthrough/generate-pdf.sh, web-docs/walkthrough/index.adoc
Add Scale [walkthrough](https://ngageoint.github.io/scale/walkthrough/output/index.html) table of contents.
Documentation
Apparently when I removed the author line from the Scale walkthrough and left a blank line between the document title and attributes, that broke an AsciiDoc convention, causing the table of contents to not get rendered. This PR removes that blank line. I have also applied the walkthrough stylesheet to the generated PDF.
=> Add table of contents to Scale walkthrough 

scale/README.md, scale/scale/settings.py, scale/scheduler/scale_scheduler.py
Scale Scheduler
Moved the hard-coded value for max connections in the scheduler to an environment variable.
The hope is that by increasing this number that when a leader election happens that takes an extended amount of time, the framework will not be marked inactive.
=> Moved value to environment variable.

scale/recipe/definition/json/definition_v6.py, scale/recipe/definition/node.py
* Scale Recipe version 6
Add better error messages for recipe type creator.
=> #1857 - Better Error Messages 

scale/job/models.py, scale/scheduler/scheduling/manager.py
Added a condition for skipping of the the `sharedmem`, where its only removed if the value is 0. Also added a check for `sharedmem` when looking for invalid resources. Addresses issue [#1826](https://github.com/ngageoint/scale/issues/1826)
=> Sharedmem skip

Dockerfile, scale/pip/docs.txt
This change allows docs to build properly. Extra requirements were backported to Scale 5.x that aren't compatible with Python 2.7 (not sure how it's working in Scale 7). It seems like Scale 5 docs have been broken since [this commit](https://github.com/ngageoint/scale/commit/cad5f20a6af8a46e7d7ee83b5c689543236548ac#diff-75118d885980acf6bfb5d8ad825827f60e063522e2ffecbef5844e2078719a57).
Confirmed this is working by building a docker image and running it locally, enabling the webserver.
=> Fix docs build in Scale 5

scale/ingest/models.py
ingest/scan
When retrieving duplicates for scans, we were appending the returned queryset to a list instead of extending the list with all items returned.
=> Scan - Extend Don't Append
